### ISSUE TITLE
Custom element doesn't exist: slider-entity-row.  

### ISSUE THREAD

**Issue by nunokaneco** [thomasloven/lovelace-slider-entity-row#104]
Hello 

After the installation on the home assistant version 0.107.7 for a reason that I don't understand after some 5 or 10 minutes of working well, I start receiving this message  

Custom element doesn't exist: slider-entity-row. 

In a red box. 

I try to fix, with other download and replacement of the raw file even with a copy past to a new file and using the "save as" function on notepad ++ to save on the WWW folder on the HA without any success for now, I have others js files with a costume components working without any problem ....

Can you please try to help me in order to solve this issue ? 

Thank you in advance for your help ! 

Cheers

**Comment by fiservedpi** [comment]
same issue here seems like ha 0.107.1 broke something

**Comment by thomasloven** [comment]
The method to install plugins has changed a bit. The installation instructions have been updated.

**Comment by fiservedpi** [comment]
still having some issues maybe im just stupid 
![Capture1](https://user-images.githubusercontent.com/42981853/79277140-3d20f700-7e77-11ea-9801-e1cea3b4b30a.PNG)
![Capture2](https://user-images.githubusercontent.com/42981853/79277146-401be780-7e77-11ea-9a8b-9aa0e8d7ac97.PNG)
![Capture3](https://user-images.githubusercontent.com/42981853/79277160-44e09b80-7e77-11ea-90d5-c21929b2b3f6.PNG)

**Comment by thomasloven** [comment]
> 6. Click the Plus to add a new resource. The url is the path to your downloaded file. Replace `<config directory>/www/` with `/local/`.

**Comment by thomasloven** [comment]
The same guide also describes how to find this problem and debug it in the "Common Problems" section.

**Comment by inconsx** [comment]
Hi,

imported the plugin and modified the path to: /local/plugins/slider-entity-row.js
But I experience still the same issue.

Cheers

**Comment by migube** [comment]
mine is /local/community/lovelace-slider-entity-row/slider-entity-row.js

**Comment by mawildcat** [comment]
> La misma guía también describe cómo encontrar este problema y depurarlo en la sección "Problemas comunes".

Yo tengo el mismo problema, después de haber cambiado la URL me sigue dando el mismo problema..., me puede decir como solucionarlo? gracias.
