### ISSUE TITLE
any plan to support groups?

### ISSUE THREAD

**Issue by papperone** [thomasloven/lovelace-slider-entity-row#105]
it will be a great feature! I've lots of lights and I grouped them by different logic (by room, by ambiance, by type, etc.) and I like a lot this card but its unability to use with group is really annoying; for single light I use it often and it's handt, for groups I've to open the group and then use the slider from there... :(

**Comment by thomasloven** [comment]
[Light group](https://www.home-assistant.io/integrations/light.group/)
