### ISSUE TITLE
Support slider and cover buttons on same row

### ISSUE THREAD

**Issue by theone11** [thomasloven/lovelace-slider-entity-row#107]
I use this for cover control but want to see the slider and cover buttons (up/stop/down) on same row.

I currently set 2 entities to achieve this:
`  - entity: cover.roof_door`
`  - entity: cover.roof_door`
`    full_row: true`
`    type: 'custom:slider-entity-row'`

Currently there is only option for toggle on same row using
`toggle: true`

Can this can be made to support the cover buttons and if not maybe add option for
`cover: true`

**Comment by theone11** [comment]
Can this be implemented?

**Comment by theone11** [comment]
I was think something like this
![image](https://user-images.githubusercontent.com/3348953/83410244-b2905900-a41e-11ea-8d9a-80f7e88fd78d.png)

**Comment by ihaettypo** [comment]
Yes please make this happen

**Comment by DanskerUS** [comment]
Can do that with this card and buttom-card..., that would be a lot of layout duplication, and variations.

**Comment by thomasloven** [comment]
Answered in #145
