### ISSUE TITLE
Resize to preserve name over slider size

### ISSUE THREAD

**Issue by decairn** [thomasloven/lovelace-slider-entity-row#11]
The size of the slider when on the same line as the light name is static (see. toggle = true option).  This causes a readability issue on longer names (e.g. Master Bedroom Lamp 1) that end up being truncated.
Can that be more flexible to prefer full print of name over slider size, with a reasonable minimum slider length observed?

![staticslidercapture](https://user-images.githubusercontent.com/15806011/48983342-844ff180-f0a2-11e8-87f8-5d5f41f80182.PNG)

**Comment by thomasloven** [comment]
I think the current default size is a reasonable minimum length (Also, it's the same behavior as for a default `input_number` entity).
You could try using the `fulL_row` option to put the slider on a single row by its own.

**Comment by hulkhaugen** [comment]
I want to 2nd this, as the title becomes very short on mobile. Could we have the option to hide the toggle, and push the slider further to the right? I really like the idea of a dimmer slider and the toggle is not interesting in most cases. It's not very useful when the names are truncated this much imo.

**Comment by hulkhaugen** [comment]
If it's possible to get it like the "downlights" example above, and ideally with the percent value as secondary info, I would be super happy. If you're not interested in adding that feature to your card, I would appreciate if you could point me in the right direction to modify it myself. I spent a full evening trying to modify it, but I honestly don't know exactly what i'm doing and did not achieve any success.

**Comment by Knol010** [comment]
How can i hide the slider when the light is off, and show it when i toggle it on?
Thanks for the help.

**Comment by thomasloven** [comment]
`hide_when_off: true`
