### ISSUE TITLE
State Numbers not displaying with Version 12

### ISSUE THREAD

**Issue by hansomatik** [thomasloven/lovelace-slider-entity-row#113]
My Home Assistant version: 0.108.x

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Since version 12 state numbers of dimmers / shutters are not shown anymore. Rollback to Version 11 shows them again.

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ ] Have made sure I am using the latest version of the plugin.

[ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by sentinel43** [comment]
Same here.

**Comment by drthanwho** [comment]
Same issue here. On V11 looks like this    ![image](https://user-images.githubusercontent.com/22405505/81131262-df01a400-8f4a-11ea-8187-1d112926dbb5.png)

And upon updating the values disappear and the slider takes the whole length.

**Comment by sentinel43** [comment]
I don't understand why this issue is under radar :-(

**Comment by thomasloven** [comment]
> I don't understand why this issue is under radar :-(

Because people who don't ignore the issue template and specifically this:
> [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

take priority.

None of you have given me anything to work with. The best I can do is **guess** that you all have very narrow sliders, in which case the value is hidden in just the same way that the built-in home assistant slider does it.

Feel free to open a new issue with more details.
