### ISSUE TITLE
Fature request. Add an option to set numbers from 0..255 instead of 0..100

### ISSUE THREAD

**Issue by bessarabov** [thomasloven/lovelace-slider-entity-row#114]
I like this custom card, but I was surprised by the fact that this control is not working the same way as the standard sider in the entity.

The max number that you can select in this control is 100. But in the entity card the max number is 255. Here are screenshots:

![](https://user-images.githubusercontent.com/47263/79912868-63243980-842b-11ea-8aea-70f8d72113e2.png)

![](https://user-images.githubusercontent.com/47263/79912861-5f90b280-842b-11ea-877c-7396cd5c5ace.png)

As I understand the number 100 in this control means 100%. But At first it was confusing that is does not show the same numbers that are shown in the standard control in HA.

I would like to see the option to make this control use numbers from 0 to 255. ( Maybe this option can be called `range` with string values: `percent`  and `byte`, but I'm not sure that this is a best possible naming)

Here is one more thing why I want such option. I want this custom card to work the same way as the standard slider is working. It does not switch off the light when you set the minimum value on the slider. So I've added `min: 1` to `custom:slider-entity-row`. With this option is does not switch the light, but that sets the britness to the value `3` (it is quite clear why is that, the 1% of 255% is 3 (with some rounding)).

![Screenshot 2020-04-22 at 00 04 22](https://user-images.githubusercontent.com/47263/79913783-d9756b80-842c-11ea-8959-4b402bfd6927.png)

**Comment by WongGendheng** [comment]
In case you are using a MQTT dimmer, you can achieve it like that:

- platform: mqtt
  schema: template
  name:  SD-Wohnzimmer-2
  state_topic: "shellies/shellydimmer-D0A531/light/0/status"
  state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
  command_topic: "shellies/shellydimmer-D0A531/light/0/set"
  command_on_template: '{"brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}}'
  command_off_template: '{"brightness": 1}'
  brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'  

This works for my Shelly Dimmer. The slider will display 0-100%, will not turn the light off (you have to add an extra switch), and, you can even set the slider in a position you like, turn the light on after that and the light will dim for the amount you set before it was on.

**Comment by KTibow** [comment]
@bessarabov this commit fixes, consider closing: https://github.com/bessarabov/lovelace-slider-entity-row/commit/443b58bbbe84dda3f771ba009adadf6b23f9c1ff

**Comment by rolandsteinmeyer** [comment]
I think the fix is be incomplete when using hide_when_off: true.

My phillips hue lamps are also using brightness from 1 to 255

When I set 

 - entity: light.sz_rechts
    name: SZ rechts
    toggle: true
    hide_when_off: true
    type: 'custom:slider-entity-row'
    brightness_percent: false

The slider disappears when brightness is set < 3,  even when the light is still on (and it is not possible to dim up afterwards).

**Comment by thomasloven** [comment]
In 17.0.0 there's two options for lights.

`attribute: brightness_pct` - 0-100, default  
`attribute: brightness` - 0-255
