### ISSUE TITLE
group slider

### ISSUE THREAD

**Issue by jhvidb** [thomasloven/lovelace-slider-entity-row#121]
Hi Thomas

Cant figure out how to make a slider for a group entity

entities:
  - type: custom:slider-entity-row
    entity: group.kitchen  ?? (from group.yaml)

I can only use the group entity as at toggle.

Is it possible?

thanks in advance

Jonathan

**Comment by thomasloven** [comment]
https://www.home-assistant.io/integrations/light.group/

**Comment by jhvidb** [comment]
Yep, that's making a group of lights. :)

But when i add  a group i get this:

![Udklip2](https://user-images.githubusercontent.com/60229374/81846832-ffd18700-9552-11ea-81bf-e05feb867a25.JPG)

**Comment by thomasloven** [comment]
It doesn't make a group. It makes a light. `light.kitchen`.

**Comment by jhvidb** [comment]
Ah!!!
Got it! It works!
Thank you so much
