### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by tallcuss** [thomasloven/lovelace-slider-entity-row#122]
Could you please show the yaml for the "Domains" panel? 
Could you also add "name" to the list of options? 
Thanks

**Comment by thomasloven** [comment]
The domains panel is just a number of slider-entity-rows with different entities of different domains; one light, one media_player, one climate, one fan, one input_number and one input_select entity. Only the `entity:` setting is different from the example given above.

All options that [apply to all entities](https://www.home-assistant.io/lovelace/entities/#options-for-entities) apply to this one too...
I don't think that needs mentioning in the readme.
