### ISSUE TITLE
Entity name wrapped

### ISSUE THREAD

**Issue by chemelli74** [thomasloven/lovelace-slider-entity-row#123]
My Home Assistant version: 0.110.x

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Updated to latest v13

What I expected to happen:
No change in entity name display

What happened instead:
Entity name is wrapped

v12:
![image](https://user-images.githubusercontent.com/57354320/81912782-5aa8c400-95cf-11ea-8080-51bb219eff75.png)

v13:
![image](https://user-images.githubusercontent.com/57354320/81912798-609ea500-95cf-11ea-978f-b24750ad4180.png)

Simone
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ctrl50** [comment]
same issue. even while off.
![Screenshot_20200514_134118](https://user-images.githubusercontent.com/51256504/81984276-6bfeca00-95e9-11ea-845c-f01fa20167ce.png)

**Comment by 3ative** [comment]
Ditto...
**V12**
![Capture2](https://user-images.githubusercontent.com/51385971/81989608-73e45b80-9635-11ea-9a3a-fddfa01b03eb.JPG)
**V13**
![Capture1](https://user-images.githubusercontent.com/51385971/81989643-865e9500-9635-11ea-9414-1da160840eb0.JPG)

**Comment by bram2202** [comment]
Same here, running HA 0.109.6, reverted back to v12 because of this issue.
Would be nice to have a possibility to set the width of the text field.

**Comment by rpitera** [comment]
>Same here, running HA 0.109.6, reverted back to v12 because of this issue.

Based on this I reverted to v12 and noticed that this also fixed my issues with `toggle: true` not being respected.  Was wondering why all my toggles went missing and reverting to v12 fixed it.

**Comment by DSorlov** [comment]
**Workaround:** If I manually recreate the layout using vertical and horizontal stacks (and set the page to full width) and put the entities in there and use sliders it works regardless of screen size or zoom. 
**"Semiworkaround"**: If I zoom to 80% it seems to work for most of my screens but not all, but it becomes hard to hit the sliders with touch.

Perhaps this have been affected by the change in [108](https://www.home-assistant.io/blog/2020/04/08/release-108/) "Horizontal stack now handles different heights better"?

**Comment by papperone** [comment]
I confirm v13 is totally unusable as I do see only first 5/6 chars of my light name and it's impossible to know which one is which; reverting to v12 the behaviour is correct as expected. I think a proper fix is needed here...
