### ISSUE TITLE
Toggle switch to turn_on and turn_off for media_player?

### ISSUE THREAD

**Issue by billsq** [thomasloven/lovelace-slider-entity-row#125]
I've been using your plugin and it really works great!
One thing I noticed is that it seems only the lights have toggle switch to turn on and off.
According to Home Assistant documentation, media_player also has services for turn_on and turn_off, is it possible to add them to the plugin?
Thanks!

**Comment by almostserious** [comment]
On Top, some Media Players support Mute/Unmute seperate from the actual volume control. So a mute/unmute switch could be a nice touch as well.

**Comment by undulattice** [comment]
+1 for media player toggle.
Would be super sweet!

Nice work. :-)

**Comment by DanskerUS** [comment]
Both very easy to do by using button-card and this card. Works great.

**Comment by DanskerUS** [comment]
The mute button:

![Capture](https://user-images.githubusercontent.com/46925705/86502226-c6004e00-bd55-11ea-8d0e-8ba3b2dff6f6.PNG)

**Comment by thomasloven** [comment]
A mute button has been implemented for 17.0.0.

`toggle: true`
