### ISSUE TITLE
double row

### ISSUE THREAD

**Issue by patmann03** [thomasloven/lovelace-slider-entity-row#127]
Love the card been using it for over a year.

Would you be interested in adding support for a second row per entity? The slider on my small screen takes up most of the light name. It would be nice to add a small second row where the full name shows and then have room for the slider on the second row. If not no big deal. If there is a way to do this currently would you mind showing me how?

**Comment by theone11** [comment]
Just define the entity twice. Once with status and the second just slider.

**Comment by thomasloven** [comment]
That's the answer. If you want two rows, use two rows.
