### ISSUE TITLE
Show grayed toggle when entity is unavailable

### ISSUE THREAD

**Issue by adrez99** [thomasloven/lovelace-slider-entity-row#130]
When toggle is visible and the entity is unavailable, instead of showing a grayed toggle the entity state is shown. It should behave as HA's entity card.
![screenshot](https://user-images.githubusercontent.com/59739805/83166194-d6962680-a10e-11ea-95e5-027e38e90b0b.png)

**Comment by DanskerUS** [comment]
I much prefer the preset behavior...

**Comment by KTibow** [comment]
Here's the line: https://github.com/thomasloven/lovelace-slider-entity-row/blob/master/src/main.js#L93
I'm sending in a PR to capitalize it.

**Comment by adrez99** [comment]
> Here's the line: https://github.com/thomasloven/lovelace-slider-entity-row/blob/master/src/main.js#L93
> I'm sending in a PR to capitalize it.

The problem isn't the text case, because there shouldn't be any text, there should be a toggle

**Comment by KTibow** [comment]
@adrez99 this is `slider-entity-row`, not `toggle-entity-row`. Do you mean a disabled slider?

**Comment by adrez99** [comment]
> @adrez99 this is `slider-entity-row`, not `toggle-entity-row`. Do you mean a disabled slider?

I know it's not toggle-entity-row, but if toggle is activated as in the example on the attached image, there should be a toggle, not?
In the attached image the top entity is ha's default light toggle and the bottom one is slider-entity-row with toggle set to true, I expect them to behave equally

**Comment by KTibow** [comment]
Yes, you're right. But then couldn't you use the built-in option instead of `slider-entity-row`?

**Comment by adrez99** [comment]
> 
> 
> Yes, you're right. But then couldn't you use the built-in option instead of `slider-entity-row`?

I'm using slider-entity-row because it has a slider, the built-in option doesn't have it.
Look at the different options:

![haslider](https://user-images.githubusercontent.com/59739805/87850104-d84dc080-c8ed-11ea-9c5b-bec09b86d532.png)

When the entity is unavailable, slider-entity-row is not following the pattern
- If toggle is enabled, a disabled toggle should be shown (this issue)
- If showing the state, it is not translated (issue #93)

**Comment by KTibow** [comment]
I sent in a PR to fix #93... Probably will take a while for @thomasloven to merge it though.
