### ISSUE TITLE
 show extra attribute value 

### ISSUE THREAD

**Issue by eddetollenaer** [thomasloven/lovelace-slider-entity-row#131]
Hi,
I love this module. Thank you..
What I think would be great is to have the possibility to select two attributes:
One for showing a value and
one that shows a value and van be controlled by the slider. 
This way you can see the current room temperature and use the slider to set the temperature of the thermostat higher or lower. 

Currently you can only see the status of the thermostat while I think that the current temperature of the room is also interesting to see. 

Thank you for your hard work!

**Comment by thomasloven** [comment]
I think the risk of confusion is too high.
It's better to add another row which displays the other value.

**Comment by eddetollenaer** [comment]
Okay, thank you.

**Comment by eddetollenaer** [comment]
Tried it, but it does not work. What I am missing is information like this:

![574BA829-DEEB-4EBC-9348-91A3060A95EF](https://user-images.githubusercontent.com/6059064/84081046-89069d00-a9dd-11ea-9d19-63be6fb6dddc.jpeg)

**Comment by thomasloven** [comment]
Then put that on a different row.
Add this to your card, THEN add a slider below it.
There's no way you'd be able to squeeze all of that into one line anyway.
