### ISSUE TITLE
js error: cannot read property 'state' of null

### ISSUE THREAD

**Issue by ktownsend-personal** [thomasloven/lovelace-slider-entity-row#132]
My Home Assistant version: **0.110.4**
My lovelace configuration method (GUI or yaml): **GUI**
What I am doing: **viewing lovelace page**
What I expected to happen: **no javascript errors**
What happened instead: **javascript errors on every page load**
**Minimal** steps to reproduce: **aside from having the slider-entity-row in an entities card, nothing else special.**

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:
```
Uncaught (in promise) TypeError: Cannot read property 'state' of null
    at HTMLElement.render (slider-entity-row.js:21)
    at HTMLElement.update (app.17c6ec83.js:2)
    at HTMLElement.performUpdate (app.17c6ec83.js:2)
    at HTMLElement._enqueueUpdate (app.17c6ec83.js:2)
```
Snippet of specific code where error occurs:
```js
    <div class="wrapper" @click=${t=>t.stopPropagation()}>
-->   ${"unavailable"===t.stateObj.state?a`
            <span class="state">
            unavailable
            </span>
        `:a`
            ${this._config.hide_when_off&&t.isOff||!t.hasSlider?"":s}

            ${this._config.toggle?t.hasToggle?i:"":(this._config.hide_state||this.hide_state)&&!1!==this._config.hide_state?"":a`
                    <span class="state">
                      ${t.string}
                    </span>
                  `}
          `}
    </div>

```

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ktownsend-personal** [comment]
### Update: 
I should have done this before submitting the initial report, but I spent some time trying to determine if it was a specific instance of the slider-entity-row that I was using (I had like 10 or so in one entity card). It turns out I had a device that was no longer available. I wasn't able to see that in the UI until I reverted every single slider to the default entity UI. *Fixing that entity reference resolved my error.* 
### Recommend:
It would be a useful improvement to the slider-entity-row if it would show the same yellow box with "entity not available: xxxx" that the standard Lovelace UI does so that the problem is more obvious and easier to troubleshoot.

**Comment by bdraco** [comment]
https://github.com/thomasloven/lovelace-slider-entity-row/blob/3dfaa1a18be246ff6c92ef248852cfcfeb3c5db0/src/main.js#L79

`c.stateObj.state === "unavailable"`

Maybe a check to see if `c.stateObj` is null?

**Comment by bdraco** [comment]
Thanks @thomasloven  👍
