### ISSUE TITLE
Lovelace not showing slider for cover entity

### ISSUE THREAD

**Issue by vansen** [thomasloven/lovelace-slider-entity-row#133]
My Home Assistant version: 0.XXX.X
Using IOBroker

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Trying to configure a cover switch for my Fibaro roller shutter 3. It is configured correctly with Zwave and I can open/close using IOBroker. I configured the following object zwave.0.NODE2.SWITCH_MULTILEVEL.Level_1 as cover for lovelace. The type is "state".
My code is the following:

`
type: entities
entities:
  - type: 'custom:slider-entity-row'
    entity: cover.Shutter_EG_Level_Dining
    attribute: position
`

What I expected to happen:
I expect to see a slider within the card.

What happened instead:
I do not see a slider. I can only see the cover icon and the name. Also with other options I cannot get a slider to show up.

I suspect this is a bug?

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
The slider is only shown for covers which can report and set their position. Not just open and close.
