### ISSUE TITLE
Feature Request: Hide when unavailable

### ISSUE THREAD

**Issue by eddetollenaer** [thomasloven/lovelace-slider-entity-row#135]
Is it possible to hide the whole entity when the entity is unavailable? I have some lights that are sometimes unavailable if a switch is turned off. It would be nice if you do not see it in the list of entities at that moment.

![Schermafbeelding 2020-06-12 om 08 13 04](https://user-images.githubusercontent.com/6059064/84470940-a741f680-ac84-11ea-8fe9-fa9154476fdd.png)

**Comment by thomasloven** [comment]
https://www.home-assistant.io/lovelace/entities/#conditional
https://www.home-assistant.io/lovelace/entity-filter/
https://github.com/thomasloven/lovelace-auto-entities

**Comment by eddetollenaer** [comment]
I know, but this does not work within an entities list on your slider-entity-row right?

**Comment by thomasloven** [comment]
What did you try so far?

**Comment by eddetollenaer** [comment]
Indeed you are right.... New to this, but you helped me with this. Thank you!
