### ISSUE TITLE
Add and configure card via graphical lovelace editor

### ISSUE THREAD

**Issue by analogue** [thomasloven/lovelace-slider-entity-row#136]
Are there any plans to make this custom component available/configurable via the graphical card configuration?

https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-card#graphical-card-configuration

**Comment by thomasloven** [comment]
Thanks, I wrote that 😃.

There's currently no way to add a graphic editor to a custom entity row, unfortunately.
If there ever is, though, this will be a prime candidate.

**Comment by theone11** [comment]
custom calendar-card seems to have one
https://github.com/ljmerza/calendar-card
![image](https://user-images.githubusercontent.com/3348953/84997157-dc53ba80-b156-11ea-920c-e5b7dd93f8b0.png)

**Comment by thomasloven** [comment]
Yes. That is a **card** this is a **row**.
