### ISSUE TITLE
add invert: true (for domain cover)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-slider-entity-row#137]
Plase consider adding an option `invert: true`. Covers have 100% position when fully opened, while logic would seem to dictate the position would be added to the % of being covers being closed....

see this for the position in HA now, on a fully opened cover:

<img width="357" alt="Schermafbeelding 2020-06-27 om 16 22 48" src="https://user-images.githubusercontent.com/33354141/85924413-766fdd00-b892-11ea-838c-f5711f1df4a0.png">

while the Ikea app shows it like this:

![20200627_142134000_iOS](https://user-images.githubusercontent.com/33354141/85924438-93a4ab80-b892-11ea-9849-e8c9c9043b71.jpg)

the latter feels better imho, and reflects the way on/off for a light or switch would compare to open/closed for a cover.

A simple inversion might could solve this?

thanks for considering

**Comment by thomasloven** [comment]
See #64 and #75 and #134.

**Comment by Mariusthvdb** [comment]
pardon me, missed those... really sorry

**Comment by thomasloven** [comment]
No worries.
