### ISSUE TITLE
Humidifier support?

### ISSUE THREAD

**Issue by KTibow** [thomasloven/lovelace-slider-entity-row#140]
I'm using the pending merge generic_hydrostat integration for my humidifier, but since the default card is bulky, I was trying to do this with this card. It says that it's unsupported. Any plans to add this new feature?

**Comment by thomasloven** [comment]
I'll consider it when and if home-assistant/core#36759 is merged.

**Comment by mdallaire** [comment]
I just wanted to add support for this and bump the topic since humidifier is now merged.
