### ISSUE TITLE
Slider state shows too much precision

### ISSUE THREAD

**Issue by j9brown** [thomasloven/lovelace-slider-entity-row#142]
My Home Assistant version: 0.113.1

My lovelace configuration method (GUI or yaml): yaml

What I am doing:

I'm presenting an "input_number" with step size of 0.2.

What I expected to happen:

The UI should show nice round numbers like "0.2" or "7.6".

What happened instead:

The UI sometimes shows excess floating point number precision like "7.599999999" depending on how the state value was updated.

Ideally the state should be presented with an appropriate number of significant digits.  For input number sliders we know the value should be a multiple of the step size so that provides a clue to the number of significant digits required.

Alternatively, this could be remedied by allowing the user to provide a state template to customize the formatting to their satisfaction.

**Minimal** steps to reproduce:

Create an input_number helper with a step size of 0.2 and a range of 0 to 11.  Use the "input_number.increment" service to repeatedly increment the value.  Because 1/5 isn't a nice binary fraction, eventually the state value will accumulate enough floating point error that it will show up in the formatting.

(https://www.home-assistant.io/integrations/input_number)

```yaml
# The least amount of code possible to reproduce my error
      type: 'custom:slider-entity-row'
      entity: input_number.media_video_volume_level
      hide_state: false
# End of code
```

Error messages from the browser console:

None.
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Is this still an issue?

**Comment by j9brown** [comment]
Not sure.  I worked around the problem locally.  Fixing it for really could perhaps take the form of rounding the state value after each update operation to minimize accumulated error or rounding it at time of presentation to the user.
