### ISSUE TITLE
vertical option

### ISSUE THREAD

**Issue by ktownsend-personal** [thomasloven/lovelace-slider-entity-row#144]
I want to have a vertical slider in my picture elements card, but I found that the input doesn't work correctly if I rotate this element with a css transform. Might it be possible to have a vertical version of this control, with icon at the top, the slider underneath and optional state below the slider? Alternatively, if there is a way to get the input to work correctly when I use a css rotation transform I can live with that as the solution.

**Comment by thomasloven** [comment]
See the answer and explanation in pinned issue #126

**Comment by ktownsend-personal** [comment]
I suspected the slider itself was the limiting factor. I'm surprised nobody has created a vertical slider for Home Assistant.

**Comment by thomasloven** [comment]
Yeah. This is the closest think I know about: https://github.com/DBuit/light-popup-card
