### ISSUE TITLE
Creating a Slider with cover buttons and slider ?

### ISSUE THREAD

**Issue by Soylor** [thomasloven/lovelace-slider-entity-row#145]
Is it possible joining both?
![image](https://user-images.githubusercontent.com/9199475/90333882-b9644c00-dfc9-11ea-9e99-13b0d3654f87.png)
Someting like joinning and getting buttons and slider like this (visually?)
![image](https://user-images.githubusercontent.com/9199475/90333896-def15580-dfc9-11ea-80a8-da171e8527ee.png)

**Comment by marcmontecalvo** [comment]
I'm looking to do the same basic thing.  Have the slider and the arrows on the same line.

**Comment by theone11** [comment]
I opened the same issue #107 about 5 months ago

**Comment by thomasloven** [comment]
Just use two separate rows.
Set the name to " " and the icon to one that doesn't exist.
