### ISSUE TITLE
Extra Toggle

### ISSUE THREAD

**Issue by carlba** [thomasloven/lovelace-slider-entity-row#148]
Would you be willing to consider adding an extra customisable toggle. I use the plugin for a fan but in addition to a speed setting it also has a setting for oscillation. It would be neat if a custom extra toggle could be added. I suppose it would have to support a on off action and a possibility to link it to a certain state.

If time is an issue would you accept PR:s in this direction or do you think this is outside the responsibility of this custom card?

**Comment by thomasloven** [comment]
Hi. Thanks for your suggestion, but I feel that would make this row too complex.

You could achieve the same functionality with a carefully crafted [template light](https://www.home-assistant.io/integrations/light.template/).
