### ISSUE TITLE
Custom element doesn't exist: slider-entity-row.

### ISSUE THREAD

**Issue by marconemariellone** [thomasloven/lovelace-slider-entity-row#149]
Hi, can anyone help me please?

My Home Assistant version: 0.114.3

My lovelace configuration method (GUI or yaml): GUI

What I am doing: I try to install via HACS and it doesn't work. When i try to create entities it show "custom element..."

![image](https://user-images.githubusercontent.com/70100399/91666693-12ba9800-eaff-11ea-9e4e-8a0cc4b8cbc6.png)

**Comment by thomasloven** [comment]
Did you refresh your browser window?

**Comment by marconemariellone** [comment]
Yes! Now it works. With HACS you just have to install it and reboot. No javascript or configuration changes. Thanks.

**Comment by nunokaneco** [comment]
> Yes! Now it works. With HACS you just have to install it and reboot. No javascript or configuration changes. Thanks.

Can you please let me know the name in the HACS ? 
Thank you and best regards
