### ISSUE TITLE
Slider for cover

### ISSUE THREAD

**Issue by pepeEL** [thomasloven/lovelace-slider-entity-row#15]
Is any chance to implement slider for cover that show also buttons and slider in the same time ?
As show on image...
![e64ccc29363d73e61f350be05163045d595c6281](https://user-images.githubusercontent.com/16692223/49374175-d0351300-f700-11e8-9bd6-bd33f4312e84.png)

Now in config i must add two items to have also slider and also standard buttons.

**Comment by pepeEL** [comment]
or as this
![cover](https://user-images.githubusercontent.com/16692223/49374363-61a48500-f701-11e8-8374-0857ad1a6d6b.jpg)

**Comment by batizisanya** [comment]
@pepeEL You can do it. Use this snipet: `- show_header_toggle: false
        entities:
          - cover.blinds1
          - full_row: true
            type: 'custom:slider-entity-row'
            entity: cover.blinds1
        title: Borító
        type: entities` And this will look like this: 
![image](https://user-images.githubusercontent.com/16525148/51614115-4dbd1880-1f25-11e9-9a55-046af0239d58.png)

**Comment by pepeEL** [comment]
My code is as this:
`entities:
  - entity: cover.cover_by_marek_v20_0_1
  - entity: cover.cover_by_marek_v20_0_1
    full_row: true
    type: 'custom:slider-entity-row'
  - entity: cover.cover_by_marek_v20_0_2
  - entity: cover.cover_by_marek_v20_0_2
    full_row: true
    type: 'custom:slider-entity-row'
  - entity: cover.cover_by_marek_v20_0_3
  - entity: cover.cover_by_marek_v20_0_3
    full_row: true
    type: 'custom:slider-entity-row'
  - entity: cover.cover_by_marek_v20_0_4
  - entity: cover.cover_by_marek_v20_0_4
    full_row: true
    type: 'custom:slider-entity-row'
  - entity: cover.cover_by_marek_v20_0_5
  - entity: cover.cover_by_marek_v20_0_5
    full_row: true
    type: 'custom:slider-entity-row'
  - entity: cover.cover_by_marek_v20_0_6
  - entity: cover.cover_by_marek_v20_0_6
    full_row: true
    type: 'custom:slider-entity-row'
  - entity: cover.cover_by_marek_v20_0_7
  - entity: cover.cover_by_marek_v20_0_7
    full_row: true
    type: 'custom:slider-entity-row'
  - entity: cover.cover_by_marek_v20_0_8
  - entity: cover.cover_by_marek_v20_0_8
    full_row: true
    type: 'custom:slider-entity-row'
show_header_toggle: false
title: Rolety parter
type: entities`

**Comment by thomasloven** [comment]
Please provide a screenshot. I don't understand your description of the problem.
