### ISSUE TITLE
Dual Slider

### ISSUE THREAD

**Issue by garyt72** [thomasloven/lovelace-slider-entity-row#150]
Could you add a "Dual Slider" option - with a 2nd entity?  Use case would be where two values (min/max) are needed.  For example, "auto" mode on a thermostat schedule (heat/cool settings) or volume limits, etc.

**Comment by thomasloven** [comment]
And why can't you use two rows?

**Comment by garyt72** [comment]
Thanks for the quick response.  I can, and am using two rows now. just started building up a package to create a simple thermostat scheduler, and was thinking that combining both upper and lower temp settings to a single row would look cleaner and cooler in the interface.  I completely and freely admit I'm being picky and it's not a necessity.

I love, use and appreciate all of the work you've done to contribute to Home Assistant.  If this isn't feasible I understand.

**Comment by thomasloven** [comment]
As per the lovelace design guidelines an entities card row should be 50 px high. Adding a second slider to that would make it pretty much unusable - specifically on a touch interface.

Will not fix. Using two rows is the preferable method.
