### ISSUE TITLE
0.116 Breaking Changes

### ISSUE THREAD

**Issue by homecb** [thomasloven/lovelace-slider-entity-row#152]
Beginning HA 0.116 all custom Lovelace cards (at least those that I use), including this one, no longer work.

The 0.116 release notes included a link to a [blog post](https://developers.home-assistant.io/blog/2020/10/02/lazymoreinfo/) explaining the (breaking) changes.

I do not consider this as a bug per se, but was wondering what the developer's plans are regarding this matter. I ask in light of the [recent announcement](https://community.home-assistant.io/t/custom-header/155399/1100) that the developer of Custom Header has decided to stop working on the project.

Thanks, Thomas for your work.

**Comment by thomasloven** [comment]
Cannot reproduce. Slider-entity-row works with 0.116.

**Comment by homecb** [comment]
After a dramatic initial post I now I feel like a complete idiot.

I tried upgrading again (this time to 0.116.1 after reverting to 0.115.6)  and everything works fine. My upgrade to 0.116 which I tested twice both produced the same results - `custom element does not exist`.

Apologies for the trouble and thanks again for your work.

Closing the ticket.

**Comment by thomasloven** [comment]
No worries. I appreciate your concern and effort to provide a fix.

... but I *introduced* part of that breaking change, and devised the workaround... 😉
