### ISSUE TITLE
Text (Number) on Slider carriage too big.

### ISSUE THREAD

**Issue by 3ative** [thomasloven/lovelace-slider-entity-row#156]
My Home Assistant version: 0.116.0

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Moving the Slider :)
I thought It maybe a Theme/Frontend issue and I've tried different Themes, same result.

What I expected to happen:
Text on Slider carriage to fit within panel(s)

What happened instead:
Text on Slider carriage encroaches under element(s) above. See image:
![Slider_number](https://user-images.githubusercontent.com/51385971/95669884-140ac600-0b7d-11eb-8a40-d66fb62e0cb8.jpg)

Q: Is this 
**Minimal** steps to reproduce:
Click and drag Slider

```yaml
# The least ammount of code possible to reproduce my error
N/A


# End of code
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ipa64** [comment]
Hi, same issue for me, is it a workaround ?

**Comment by thomasloven** [comment]
This is an upstream problem in Home Assistant: https://github.com/home-assistant/frontend/issues/7560
