### ISSUE TITLE
 UI editor is not supported for this config: 

### ISSUE THREAD

**Issue by fireheadman** [thomasloven/lovelace-slider-entity-row#158]
Installed the integration through HACS...
This inserts the Resource automajically.

When I follow your example, I end up with a lot of messages....   Are these considered INFO only?
The sliders appear to work, but it seems a bit disturbing to see debug-type messages in the editor when I use this card.

![image](https://user-images.githubusercontent.com/19847195/95905068-9817a600-0d55-11eb-9b8b-ed5271db0997.png)

**Comment by thomasloven** [comment]
That warning is from Home Assistant, not from slider-entity-row.
It will be different in 0.117
