### ISSUE TITLE
When full row is used in a vertical stack card bg is not used

### ISSUE THREAD

**Issue by skynet01** [thomasloven/lovelace-slider-entity-row#16]
If you are stacking cards the styling is not being honored so it looks like sliders are not part of the card 
example: http://secure.fabriceleven.com/BY5uIn

**Comment by thomasloven** [comment]
Please provide a sample configuration as well.

**Comment by Mikei386** [comment]
It seems the problem only happens when card-modder is in use:

`      - type: custom:card-modder
        card:  
          type: custom:vertical-stack-in-card
          cards:
            - type: custom:slider-entity-row
              entity:  light.deckenlampe_buero
              name: Deckenlicht
              full_row: false
              toggle: true
            - type: custom:slider-entity-row
              entity:  light.deckenlampe_buero
              name: Deckenlicht
              full_row: false
              toggle: true
        style:
          "border-radius": "0px"  `

**Comment by Mikei386** [comment]
It seems to be happening when card-modder is in use:
 
     - type: custom:card-modder
        card:  
          type: custom:vertical-stack-in-card
          cards:
            - type: custom:slider-entity-row
              entity:  light.deckenlampe_buero
              name: Deckenlicht
              full_row: false
              toggle: true
            - type: custom:slider-entity-row
              entity:  light.deckenlampe_buero
              name: Deckenlicht
              full_row: false
              toggle: true
        style:
          "border-radius": "0px"

**Comment by Mikei386** [comment]
I have exactly the same problem:

      - type: vertical-stack
        cards:
          - type: custom:slider-entity-row
            entity:  light.deckenlampe_buero
            name: Deckenlicht
            full_row: false
            toggle: true
          - type: custom:slider-entity-row
            entity:  light.deckenlampe_buero
            name: Deckenlicht
            full_row: false
            toggle: true

First I thought it had something to do with the card-modder plugin but it seems to happen as soon as you use a stacked card.

**Comment by thomasloven** [comment]
This is not a card.
The slider-*entity-row* is a *row* to be used in an *entities* card.
Please check the sample configurations in the readme.

**Comment by skynet01** [comment]
yeah i used it the same way

**Comment by thomasloven** [comment]
Mystery solved then.
