### ISSUE TITLE
Switch dimmer future supported 

### ISSUE THREAD

**Issue by MiAutomations** [thomasloven/lovelace-slider-entity-row#163]
I have tested this integration for a zigbee dimmer and I'm receiving this message:
```
Unsupported entity type: switch
type: 'custom:slider-entity-row'
entity: switch.smart_plug_14
```
Thank you for your support and best regards

**Comment by thomasloven** [comment]
That's a limitation in home assistant. Switches switch things. Lights dim.
https://www.home-assistant.io/integrations/light.switch/
