### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by ma14789** [thomasloven/lovelace-slider-entity-row#166]
Hi,

My Home Assistant version: 0.107

My lovelace configuration method (GUI or yaml): yaml

What I am doing:

I display text associated with a "input_number"
![Capture](https://user-images.githubusercontent.com/76993177/103627796-62422200-4f3e-11eb-8ced-3293ba0f8cae.PNG)

I would like to be able to display the text completely. I started searching with the following code:
![Capture3](https://user-images.githubusercontent.com/76993177/103627832-6cfcb700-4f3e-11eb-9e0a-5ef78be974f1.PNG)

What happened instead:
![Capture2](https://user-images.githubusercontent.com/76993177/103627865-7a19a600-4f3e-11eb-930a-044671465324.PNG)

**Comment by thomasloven** [comment]
What does this have to do with slider-entity-row?

**Comment by ma14789** [comment]
Oh I'm sorry I was wrong, this is related to lovelace-layout-card!

I move my request
