### ISSUE TITLE
tap_action

### ISSUE THREAD

**Issue by wbilger** [thomasloven/lovelace-slider-entity-row#17]
Feature request.

Would be greate to have the ability to change tap_action.
Use case would be on mobile, where there is not really room to show name, slider, percentage, and toggle, so it would be great to be able to change tap_action to toggle instead of more_info. Also, for a slider, besides state_info, the more_info screen is irrelevant.

**Comment by Zahzi** [comment]
I would love to be able to tap the icon to toggle on/off and long press to pull up more_info, similar to the default light entity.

**Comment by leothlon** [comment]
i second this, also ability to remove the % at the end would be nice, to make more room for entity name.
i have afew sliders in a folding entity row, and that gives verry little room for name now.

**Comment by hulkhaugen** [comment]
Great suggestions, I have also commented in a similar post. Personally I have made a modified version where you can hide the toggle/level to have the slider move further to the side, as well as set slider length. It's still not finished, as I also want to have level percentage as secondary info. I'll look at your suggestions as well. Hopefully Thomas can implement this, as he knows what he's doing as opposed to me.

**Comment by thomasloven** [comment]
This will probably happen by itself as soon as Home Assistant implements support for selecting tap_action of entities - which should be soonish.

**Comment by thomasloven** [comment]
In the meantime, I've increased the unclickable area so that you can't accidentally toggle the entity by clicking between 16 and 20 pixels above the slider...
