### ISSUE TITLE
Feature - Make toggle control different entity

### ISSUE THREAD

**Issue by xatr0z** [thomasloven/lovelace-slider-entity-row#170]
The title says it all. I find myself using lots of lights that are (also) controlled by automations. Like movement detection which turns the light off after no motion is detected for a certain time.
Sometimes this is undesirable and in that case I dont want to spent time going to my automations and finding the right one.

I would like to be able to use the toggle to turn the automation (or an input_boolean) on and off. So the toggle controlling an different entity than the slider.

**Comment by thomasloven** [comment]
This can be done with a carefully crafter [template light](https://www.home-assistant.io/integrations/light.template/).

**Comment by thomasloven** [comment]
Or you could just use two rows, one for each entity 🤷
