### ISSUE TITLE
Slider with toggle does not fit in card

### ISSUE THREAD

**Issue by circa1665** [thomasloven/lovelace-slider-entity-row#171]
My Home Assistant version: 2021.2.0

My lovelace configuration method (GUI or yaml): YAML

What I am doing: Previous to core 2021.2.0, slider with toggle would fit within the boundary of a card, now it spills over.
<img width="304" alt="toggle cut off" src="https://user-images.githubusercontent.com/33236082/106937954-4933b900-6716-11eb-8e52-59133606ab5d.png">

**Minimal** steps to reproduce:

```yaml
type: entities
entities:
  - type: 'custom:slider-entity-row'
    entity: light.light
    toggle: true
    name: Light
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Slider-entity-rows assumes that if you go through the trouble of using a **slider**-entity-row instead of just a row, it's because you want the **slider**.

So when squeezed down into a way too narrow card it will try to keep the slider useable as far as possible, and make the other stuff move over. Due to limitations in lovelace, the name can't be made more narrow, so this is the only alternative.

**Comment by Pitchshift** [comment]
@thomasloven I am facing the same issue. Previously the configuration using a toggle worked without anything displaying off the edge of the screen. I think an update to HA broke it. Even if you turn off the toggle, the current slider status doesn't display fully using a mobile view (arguably the way most people use HA).

![HA Slider](https://user-images.githubusercontent.com/34736642/110313679-af09ae00-7ffe-11eb-8e18-6f952130987f.png)
