### ISSUE TITLE
Add support of number platform

### ISSUE THREAD

**Issue by Spirituss** [thomasloven/lovelace-slider-entity-row#172]
It would be great to add newly announced platform number, especially mqtt number (https://www.home-assistant.io/integrations/number.mqtt/#retain). With slider in gui mqtt number is a great tool for number parameters that should be synchronised between some HA instances, for example. 
With number it should work the same way as with input_number.

**Comment by Spirituss** [comment]
@thomasloven 
Please, reopen it. The lovelace-slider-entity-row doesn't allow to use numbers more than 100 nor non-integral numbers as it does with input_numbers.

**Comment by Spirituss** [comment]
I re-tested, the issue is not solved yet.

**Comment by thomasloven** [comment]
I can't reproduce this problem.

**Comment by Spirituss** [comment]
> I can't reproduce this problem.

Thanks, Thomas!
I updated my HA. It works well in HA 2021.6 in case when min/max are defined in MQTT number.
