### ISSUE TITLE
New Feature: Adding group to the available entity domains

### ISSUE THREAD

**Issue by the-bort-the** [thomasloven/lovelace-slider-entity-row#173]
Looking to suggestion the feature of adding the slider to the groups entity domain. Sometimes I have more than three lights in a group and it'd be nice to slide the brightness of all of them at once. Currently I'd have to slide each, say 10 lights, down from full brightness to 50%. We can turn them off at once, it'd be useful, I believe, to be able to slide their brightness as one entity.

**Comment by thomasloven** [comment]
https://www.home-assistant.io/integrations/light.group/
