### ISSUE TITLE
Add support for new fan API

### ISSUE THREAD

**Issue by galak** [thomasloven/lovelace-slider-entity-row#175]
HA 2021.3 has changed the fan API

https://www.home-assistant.io/integrations/fan/

Get the following message in log:

`Calling fan.turn_on with the speed argument is deprecated, use percentage or preset_mode instead`

**Comment by mikelawrence** [comment]
In a related note. New percentage based fans do not work properly with this slider.

**Comment by BigManDave** [comment]
I'm also hoping for a way to configure the slider to use percentage instead of presets.

**Comment by matt-cantu** [comment]
I'm also hoping for an update that will support the usage of percentages. Prior to the release of Home Assistant version 2021.3.x, I was able to use the custom slider to choose between 0-7 for my Haiku/SenseMe fan. Now I only see 0-4.
