### ISSUE TITLE
Have some way of mapping percent values to a different scale

### ISSUE THREAD

**Issue by galak** [thomasloven/lovelace-slider-entity-row#178]
I've got a fan that has speeds 1-7, as percentages this shows up as 0(off), 14, 29, 43, 57, 71, 86, 100.  Would be nice if visually this could be 1, 2, 3...7 instead.

**Comment by thomasloven** [comment]
How does it show up in the more-info card for the fan?

**Comment by galak** [comment]
Here's a screenshot of what it looks like:
![Screen Shot 2021-03-16 at 6 29 11 AM](https://user-images.githubusercontent.com/16417047/111302288-366ba880-8621-11eb-9af8-b380d7e71cbb.png)

**Comment by galak** [comment]
@thomasloven any more thoughts on this?

**Comment by thomasloven** [comment]
Slider-entity-row shows what Home Assistant knows. You'd have to make home-assistant understand your levels first - through a template entity or an input_select or something, and then slider-entity-row will show it the way you want.
