### ISSUE TITLE
slider for input-number

### ISSUE THREAD

**Issue by abattech** [thomasloven/lovelace-slider-entity-row#18]
Hmm, slider does not support input-number? That would be very useful!

**Comment by thomasloven** [comment]
Input-number shows up as a slider by default in lovelace.

**Comment by abattech** [comment]
Well, yes. But  do I get the same customizability in lovelace as in your card? E.g. I need full-row = true....

**Comment by thomasloven** [comment]
Fair enough... I'll see what I can do.
