### ISSUE TITLE
Option to hide slider when off

### ISSUE THREAD

**Issue by matthew-larner** [thomasloven/lovelace-slider-entity-row#182]
It would be great if you could hide the slider if the item is off/at 0%.

**Comment by matthew-larner** [comment]
I just realised you could use `hide_when_off: true` to do this. Would be really helpful to include that in the docs more clearly.

Thanks!

**Comment by thomasloven** [comment]
Reopening this to remind me that this should definitely be in the readme.

**Comment by luwidgiani** [comment]
did something go wrong with this? it's default on instead of off or something.
i just updated to 2021.6.3 and all my sliders are missing

i have the default config
  - type: custom:slider-entity-row
    entity: light.bureau_licht
    name: Algemeen
and my sliders are gone, i have to click the entity, toggle it on, and then the slider appears

**Comment by luwidgiani** [comment]
it seems that it does work for hue lights but not for knx lights anymore, when it did work before

**Comment by thomasloven** [comment]
Sounds like an unrelated issue, and also like you should include exactly the version of slider-entity-row that *your browser console* says you have installed.

**Comment by luwidgiani** [comment]
i have installed it through hacs so i think i don't have to include the version, console tells me SLIDER-ENTITY-ROW 17.1.0 IS INSTALLED, do i have to change the reqources and add the version then?

but as you mention, It's probably a problem in knx and i was too fast reporting an issue here, i think it first have to receive a state before showing the slider.

**Comment by thomasloven** [comment]
17.1.0 is the latest, so that's good.

The way lights report their ability to dim and stuff has recently changed in Home Assistant.
Please open a separate issue about this, and please also include all of the attributes for one of your lights that are working and for one that is not.
I.e this stuff: 
![image](https://user-images.githubusercontent.com/1299821/121342514-fcf5c100-c921-11eb-8d8b-eab04883fdd2.png)

**Comment by luwidgiani** [comment]
thanks for the help, I created a topic in the community with some additional info cause it looks like an internal external address problem
https://community.home-assistant.io/t/i-have-a-different-representation-of-entity-in-lovelace-for-internal-and-external-address/314497
