### ISSUE TITLE
add confirmation (and/or lock)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-slider-entity-row#186]
Please consider as title, since the slider can be used for home entering garage doors too.... Id really love to be able to guard that with a secondary click on a confirmation:

<img width="426" alt="Schermafbeelding 2021-04-19 om 10 56 35" src="https://user-images.githubusercontent.com/33354141/115210085-8b0db200-a0fe-11eb-9c31-b80b209c2542.png">

right now this is a bit too prone to accidental opening

thanks for considering

**Comment by thomasloven** [comment]
I don't think this is within the scope of the slider-entity-row.

Try combining it with [restriction card](https://github.com/iantrich/restriction-card) or fold-entity-row, perhaps?
