### ISSUE TITLE
Add Unit label Feature

### ISSUE THREAD

**Issue by roumano** [thomasloven/lovelace-slider-entity-row#187]
First, thank you for this wonderful add-on ! 

It cosmetics, but i would like to add, if it's possible, a unit label feature, as example, i set this : 
```
  - entity: input_number.pool_water_temperature
    name: Température
    type: 'custom:slider-entity-row'
    icon: 'mdi:coolant-temperature'
    hide_state: false
```

It's show a slider and a number (like `17`). i would like a option to add a label option to see `17°C` in my example, instead of `17`

**Comment by thomasloven** [comment]
Set the `unit_of_measurement` for your input_number.
