### ISSUE TITLE
Slider shows wrong current value (at least for brightness)

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-slider-entity-row#188]
I discovered already a few weeks ago (maybe introduced with a specific HA Core or lovelace-slider-entity-row update?) that the actual brightness/percentage of lights is not shown correctly on the slider anymore.

E. g.:

Smaller column:
![grafik](https://user-images.githubusercontent.com/13799156/116795722-4f4bf280-aad7-11eb-8c9e-da99487c94fe.png)

Bigger column:
![grafik](https://user-images.githubusercontent.com/13799156/116795809-ddc07400-aad7-11eb-9cc3-d751488a8088.png)

Actual brightness: 11 %
Slider value: 28

The more popup shows the right value:
![grafik](https://user-images.githubusercontent.com/13799156/116795742-81f5eb00-aad7-11eb-991e-7e0779caf39e.png)

YAML code in use for above example:

```
  - type: 'custom:slider-entity-row'
    entity: light.licht_room_a
    name: Licht
    hide_when_off: true
    full_row: false
    min: 1
    max: 100
    step: 1
    attribute: brightness
    toggle: true
    show_state: true
    state_color: true
    secondary_info: brightness
    state_header: ''
    column: false
```

**Comment by thomasloven** [comment]
Try `attribute: brightness_pct` if you want to set the brightness in percent.
Or just leave it out. That's the default.

**Comment by bcutter** [comment]
> Try `attribute: brightness_pct` if you want to set the brightness in percent.
> 
> Or just leave it out. That's the default.

Thanks! That would be too easy :-) Will give it a try. If you don't hear anything more - that was the fault (level 8 issue) ;-)
