### ISSUE TITLE
Ability to independently control on/off and attributes from different entities 

### ISSUE THREAD

**Issue by farsonic** [thomasloven/lovelace-slider-entity-row#189]
Hi there, I can't see how to achieve this and wondering if it is a feature request. I have a lamp that has an external power switch that can be controlled using using Home Assistant but also have a LIFX bulb connected to this lamp. Can slider-entity-row have a switch to control the power on/off and sliders for the LIFX bulb. Two separate operations....

**Comment by thomasloven** [comment]
https://www.home-assistant.io/integrations/light.template/
