### ISSUE TITLE
Error when using Lovelace "Configure UI"!

### ISSUE THREAD

**Issue by aronsjoberg** [thomasloven/lovelace-slider-entity-row#19]
Hi!

I'm loving custom:slider-entity-row but I'm getting this error when I'm trying to edit a group that includes lights with type:custom:slider-entity-row:

```
Your config is not supported by the UI editor:
Expected a value of type `{entity,name,icon} | entity-id` for `entities.0.type` but received `"custom:slider-entity-row"`.
Falling back to YAML editor.
```

![image](https://user-images.githubusercontent.com/30977669/50501166-6df8d500-0a56-11e9-8bc5-c0c70136ad30.png)

Everything seems to work fine and the entity is updated, but the red text  is worrying... ;) Is there anything to do?

**Comment by thomasloven** [comment]
Custom cards are not supported by the lovelace UI configuration at this point.
