### ISSUE TITLE
Home Assistant white_value being depreciated

### ISSUE THREAD

**Issue by czech12** [thomasloven/lovelace-slider-entity-row#193]
Hello,

This isn't necessarily a bug or a feature request, I guess it's more of a question at this point.

I have been using the slider entity row for my Shelly RGBW2 controller.  Prior to updating to Home Assistant 2021.5.x, I had a slider entity row to control the RGB brightness (which was controlled by the 'brightness' property) and a second row to control the White brightness (which was controlled by the 'white_value' property).

I see that the Home Assistant "Light Entity" is depreciating the 'white_value' property [here](https://developers.home-assistant.io/docs/core/entity/light/).  There are now properties for 'rgb_color', 'rgbw_color', and 'rgbww_color'.

I guess my question is how to use slider entity row to control only the 'W' in the 'rgbw_color' property.

Thanks for your contributions to the community!

Aaron

**Comment by czech12** [comment]
This was resolved with the latest update.

![image](https://user-images.githubusercontent.com/74950455/121985093-16ec3500-cd62-11eb-8826-af3e43f416d4.png)

Thank you!

**Comment by thomasloven** [comment]
Yes.
Sorry for missing this issue.

**Comment by czech12** [comment]
> Yes.
> Sorry for missing this issue.

No problem at all.  Thanks for fixing one of my favorite cards with the quickness!
