### ISSUE TITLE
Custom element doesn't exist: slider-entity-row

### ISSUE THREAD

**Issue by ilium007** [thomasloven/lovelace-slider-entity-row#196]
My Home Assistant version: core-2021.5.5

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Trying to get a slider UI element

What I expected to happen: 

What happened instead:

Installed plugin via HACS

<img width="654" alt="image" src="https://user-images.githubusercontent.com/732766/119474081-2560b580-bd8f-11eb-92ed-7aed99137ba2.png">

<img width="981" alt="image" src="https://user-images.githubusercontent.com/732766/119473682-c00cc480-bd8e-11eb-8b5d-197315857d89.png">

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ilium007** [comment]
Everything looks as it should as far as I can see:

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/732766/119476279-41655680-bd91-11eb-8996-34f44d7cf987.png">

**Comment by maniscalcojohn** [comment]
Same problem after updating to 2021.5.5

**Comment by maniscalcojohn** [comment]
Cache reload fixed this for me...

**Comment by Trashsk** [comment]
Same issue on 2021.6, did somebody find a solution?

**Comment by doerakje** [comment]
Same issue here using HA in a Docker container.
Got triggered by this post: https://github.com/thomasloven/lovelace-slider-entity-row/issues/104#issuecomment-727626891

Changed my resources url fom:
/local/lovelace-slider-entity-row/slider-entity-row.js
to:
/local/community/lovelace-slider-entity-row/slider-entity-row.js

That did the trick for me, give it a try.

**Comment by Reedstrr** [comment]
Worked like a charm, thanks @doerakje !! 🙏🏻

**Comment by luke2700k** [comment]
> Cache reload fixed this for me...

Same for me, thought I was in for some hours of troubleshooting! I should know this by now!

**Comment by RememberTilman** [comment]
An aside for someone that comes across this:
I used HACS to install. It created the resource link within the HACS directory. 
I changed the resource to local/community (plus removed the hacstag at the end of the string) and it worked correctly.

**Comment by andrewbpowers** [comment]
Too bad... just does not work!

I have tried the following paths:
> /hacsfiles/community/lovelace-slider-entity-row/slider-entity-row.js
> /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
> /local/community/lovelace-slider-entity-row/slider-entity-row.js

None works! :-(


And this is what my Card Configuration looks like:
> type: entities
> entities:
>   - type: custom:slider-entity-row
>     entity: input_number.booster


Thanks for any help in advance!

**Comment by WongGendheng** [comment]
> Cache reload fixed this for me...

Everyone seems to ignore the "empty your browsers cache" comment. Works like a charm. Thanks my man

**Comment by githubkusi** [comment]
indeed, Shift+F5 in chrome-based browsers fixes the issue

**Comment by TCAby** [comment]
Doesn't work. 
**Custom element doesn't exist: slider-entity-row** alert

### My ui-lovelace:

resources:
  - type: module
    url: /usr/share/hassio/homeassistant/www/community/lovelace-slider-entity-row/slider-entity-row.js

########################################

- type: 'custom:slider-entity-row'
   entity: input_number.prevent_defrost
