### ISSUE TITLE
Display values

### ISSUE THREAD

**Issue by stipe76** [thomasloven/lovelace-slider-entity-row#2]
Hi there. Just wondering if there is a way to display text values? It would be nice to have a popup while sliding with the value displayed, and also a text next to the switch showing actual brightness state. Thanks

**Comment by thomasloven** [comment]
I'll have to think about the best way to do this. Dimmer values are in the range 0-255, which doesn't really make sense from a interface perspective where you'd rather have 0-100 %.

**Comment by stipe76** [comment]
Could you divide the value by 2.55 to show it in 0-100% range? This would be a great addition if you could work out a way. Thanks for you work!
