### ISSUE TITLE
Customize friendly name

### ISSUE THREAD

**Issue by kylerw** [thomasloven/lovelace-slider-entity-row#20]
add a "name" option like the default entities card

**Comment by kylerw** [comment]
apparently this already works. must have cached...

**Comment by thomasloven** [comment]
Well, you were faster than me. I'll spare you my snarky comment then. Thanks for owning up :smile:

**Comment by kylerw** [comment]
I felt pretty dumb so any snark was expected and deserved.... 🤦‍♂️
