### ISSUE TITLE
Fan Entity slider is missing the percentage display

### ISSUE THREAD

**Issue by Hypfer** [thomasloven/lovelace-slider-entity-row#200]
My Home Assistant version: 2021.5.1

My lovelace configuration method (GUI or yaml): gui

What I am doing: 

I'm using the slider-entity-row to have a slider for my fan entity

What I expected to happen:

The current percentage should be displayed right next to the slider

What happened instead:

![image](https://user-images.githubusercontent.com/974410/121521402-4f9fad80-c9f4-11eb-98a4-109582eb9876.png)

**Minimal** steps to reproduce:

```yaml
type: entities
entities:
  - entity: fan.dehumidifier_8dbe7c_setpoint
    name: Setpoint
    type: 'custom:slider-entity-row'
```

Error messages from the browser console:

---

Additional information:

![image](https://user-images.githubusercontent.com/974410/121521588-8bd30e00-c9f4-11eb-9ea1-43c7f18c8175.png)

![image](https://user-images.githubusercontent.com/974410/121521791-c0df6080-c9f4-11eb-8afa-3e9ea713a283.png)

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] Am aware that I'm abusing the `fan.mqtt` component

**Comment by Lordnnud** [comment]
I see the same issue with my lights 
![image](https://user-images.githubusercontent.com/19661440/126898575-a78d6b65-d2f5-49fb-aead-28f4c3119ddd.png)

I am running 
core-2021.7.4
supervisor-2021.06.8
Home Assistant OS 6.1
slider-entity-row 17.1.0

I've followed all the advice in issue #194. I see this in Firefox and Chrome. The slider works, just % does not reflect a value.
