### ISSUE TITLE
Documentation section for installing wtihout HACS

### ISSUE THREAD

**Issue by alive-corpse** [thomasloven/lovelace-slider-entity-row#201]
Hi! Can you please add short manual to README.md about installing without HACS?

**Comment by thomasloven** [comment]
Two years and one day ahead of you:
https://github.com/thomasloven/lovelace-slider-entity-row/commit/1d29e2365f2a843d24ead02b246868c73db27cec#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R6
