### ISSUE TITLE
Make the icon on the left a toggle on click instead of showing the details

### ISSUE THREAD

**Issue by MartinKlingeling** [thomasloven/lovelace-slider-entity-row#205]
Example:
![image](https://user-images.githubusercontent.com/80011040/124840044-5cc7a200-df8a-11eb-9c7d-1eb689f5d8f4.png)

Currently, clicking the light bulb or the text will open the details popup. To turn the light off, you have to either set the slider to 0 or open the details popup and toggle the light there. 

Proposal:
Allow the light bulb icon to act as an toggle for the light. The text will still open the details popup. This way there is a nice big target to quickly toggle the light and you can still have the brightness percentage on the right of the slider. 

The click action for other entity domains could be different. Or the click action could be configurable to cover more use cases.

**Comment by thomasloven** [comment]
The row supporst most options any other entity row does, like `name`, `icon`, and `tap_action`.

**Comment by MartinKlingeling** [comment]
It is not quite the same thing. My proposal was to be able to separately define what will happen when you tap a) the icon and b) the name. But I understand if you want to stick to standard entity-row behaviour for consistency. 

I have now set tap_action to toggle and double_tap_action to more-info for a similar effect.

**Comment by thomasloven** [comment]
Not only for consistency. That **is** a standard entity-row entirely handled by Home Assistant core.
