### ISSUE TITLE
 auto-entities and slider-entity

### ISSUE THREAD

**Issue by Bastiencc** [thomasloven/lovelace-slider-entity-row#206]
**My Home Assistant version:** 2021.7.1

**My lovelace configuration method (GUI or yaml):** yaml

**What I am doing:** Seems that auto-entities and slider-entity are not working well together : 

**What happened instead:**

**Minimal** steps to reproduce:

```
- url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
  type: js
- url: /hacsfiles/lovelace-auto-entities/auto-entities.js
  type: js
```

**Error messages from the browser console:**

```
xxx:8123/hacsfiles/lovelace-auto-entities/auto-entities.js:1:1 Uncaught SyntaxError: Identifier 'e' has already been declared
xxx:8123/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js:1:1 SyntaxError: redeclaration of const G
xxx:8123/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js:1:1 Uncaught SyntaxError: Identifier 'e' has already been declared
```
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
`type: module`

**Comment by thomasloven** [comment]
https://www.home-assistant.io/lovelace/dashboards-and-views/#type

**Comment by Bastiencc** [comment]
thanks, and sorry, I was stupid !

**Comment by thomasloven** [comment]
No worries. `js` used to be the default after all.
