### ISSUE TITLE
Combining multiple entities (switch + slider)

### ISSUE THREAD

**Issue by ardeus-ua** [thomasloven/lovelace-slider-entity-row#21]
Is this possible to use it to combine different entities? For example switch and slider (input_number)?

**Comment by Shadowpheonix** [comment]
I too would like this ability.

**Comment by aidbish** [comment]
+1 for switches

**Comment by abattech** [comment]
+1

**Comment by thomasloven** [comment]
Not without a very good use case. It sounds incredibly confusing. Why not just put them on two rows? You can even make the slider use full_row

**Comment by hulkhaugen** [comment]
Or they could make a light group and display that one as a single slider-entity-row. I'm not sure how the switch would operate, everything but 0 is on or everything >50% is on?

**Comment by thomasloven** [comment]
Three months without a compelling use case.
Closing this.

**Comment by idofr** [comment]
Hi @thomasloven 
A use case (and the reason i'd really like to see this feature) - look at the official Hue app. It allows you to control each light individually, but also control the entire room at once with a single slider at the header. I really miss this functionality

**Comment by thomasloven** [comment]
That's a very different thing that's already possible by using a light group.

**Comment by apivaral** [comment]
I have been trying what you say, but can’t get it to work like fold-entity-row, slider-entity-row doesn’t support entities like fold-entity-row, it only supports entity. I’ve also tried to put entity of individual lamps below the group, and it shows the rows always, how to show rows with lights of group only if group is ON like in fold-entity-row?

**Comment by thomasloven** [comment]
https://www.home-assistant.io/lovelace/entities/#conditional

**Comment by AngellusMortis** [comment]
Without going into the long backstory, I have a smart switch _and_ a smart light on that switch. So being able to have one entity for the slider (the light) and one entity for the toggle (the switch) would be really great for that use case. The light switch is not a dimmer switch.

**Comment by thomasloven** [comment]
Template light
https://www.home-assistant.io/integrations/#search/template
