### ISSUE TITLE
Shrink option to make the slider slight shorter?

### ISSUE THREAD

**Issue by GirzzlyAK** [thomasloven/lovelace-slider-entity-row#218]
As with `grow:` is there a way to `shrink:` to make the slider bar slightly shorter, say, the same default length of the HA default sliders? Your normal slider is slightly longer, and truncates my `name:` fields. Alternatively, can we just have a `length:` option that is a percent of full size?

**Comment by thomasloven** [comment]
The main purpose of slider-entity-row is to display a slider.
You may have a better experience with *two* rows per entity. One default one, and one with a full width slider.

**Comment by thomasloven** [comment]
![image](https://user-images.githubusercontent.com/1299821/139556930-1d0b4204-efa5-448f-b714-9eb39474dd7b.png)

**Comment by GirzzlyAK** [comment]
OK. Thanks Thomas. I'll give that a try.
