### ISSUE TITLE
Hide name/icon

### ISSUE THREAD

**Issue by PeteCondliffe** [thomasloven/lovelace-slider-entity-row#22]
Feature Request

Would it be possible to add options to remove the name and icon.

Some entities you know exactly what it is from the icon, which would leave more space for the slider without taking up the second row.

The reason I say both is because I think  it could look nice as an element on a picture-element card

**Comment by thomasloven** [comment]
Either use `full_row: true` or
```yaml
name: " "
icon: mdi:this-does-not-exist
```

**Comment by PeteCondliffe** [comment]
Such a simple solution i completely overlooked.

Thanks
