### ISSUE TITLE
Invert slider display behaviour

### ISSUE THREAD

**Issue by ZTHawk** [thomasloven/lovelace-slider-entity-row#221]
I have covers that are closed with value 0 and open with value 100 (they are following definitions at https://developers.home-assistant.io/docs/core/entity/cover/#platform-properties-to-be-implemented-by-deriving-platform-classes).
I would like to see when moving the slider to the right that the cover is not opening but closing.
So if an invert option is active then:
- the current position of the slider would be "100 - <current_position cover position>"
- updating the cover position would be "100 - <current_position of slider>"

It is similar to request #162 but this request does not aim to support "wrong" behaviour of covers, but to give the possibility to change the behaviour of the slider itself.

This inverted behaviour makes more sense from the cover visibility point of view:
When cover is fully open then it means that the cover is not visible (= 0).
When the cover is closed then it means that the cover is fully visible (= 100).

It seems that pull request #134 is doing what I am requesting.

**Comment by thomasloven** [comment]
Maybe the new `dir` option in 17.2.0 will do what you want?

**Comment by thomasloven** [comment]
Otherwise, this is what you want https://www.home-assistant.io/integrations/cover.template/

**Comment by ZTHawk** [comment]
Option "dir" will just mirror the slider but the values are all the same and you have to move the slider from right to left. This is a weird behaviour.

### **Solution**
I ended up with forking this repo and implementing it based on the pull request #134 (with some fixes).
For those that need this feature just add a custom repository to HACS "https://github.com/ZTHawk/lovelace-slider-entity-row" and replace the original one.
