### ISSUE TITLE
The main 'lit-element' module entrypoint is deprecated

### ISSUE THREAD

**Issue by chezpaul** [thomasloven/lovelace-slider-entity-row#228]
Just in case you hadn't noticed:

slider-entity-row.js:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.

**Comment by Petro31** [comment]
yep, just about to report this

slider-entity-row.js:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.

**Comment by darkkatarsis** [comment]
https://github.com/thomasloven/lovelace-slider-entity-row/pull/239[merge req fixing #228](https://github.com/thomasloven/lovelace-slider-entity-row/pull/239)

**Comment by wimb0** [comment]
Same issue here. Seems like the pull request to fix this was closed without merging,

**Comment by johntdyer** [comment]
@thomasloven  any thoughts on why that was closed ?

**Comment by thomasloven** [comment]
Fixed in 17.3
