### ISSUE TITLE
unavailable state issue

### ISSUE THREAD

**Issue by tomeeka** [thomasloven/lovelace-slider-entity-row#23]
Toggle should be hidden (slider too), if the entity is unavailable.
Now if the entity is unavailable and the toggle function is enabled, then the switch is on, which is not true.

![kep](https://user-images.githubusercontent.com/41842441/51872750-d9d2a400-235a-11e9-8b32-807da47f0368.png)

**Comment by Joeboyc2** [comment]
I'd like to see this added too

**Comment by MightyMilster** [comment]
Hi Thomas. Great card! Could you please add a "hide_when_off" option. Testing for when an entity is available/unavailable. I and others probably have light circuits controlled by something like a Sonoff; then a smart bulb in the fitting. This would be a more elegant solution that saves front end real estate when a light is off. Thanks!

**Comment by thomasloven** [comment]
There is a "hide_when_off" option. It´s `hide_when_off: true`...

**Comment by MightyMilster** [comment]
Oh. Thanks Thomas. Where are all the options documented? Doesn't seem to be
in the full readme.

**Comment by thomasloven** [comment]
It wasn't. It is now, though.

**Comment by MightyMilster** [comment]
Champion! Thank you mate! Milan

**Comment by thermseekr** [comment]
I tried `hide_when_off: true` in a media player but the slider keeps showing:

<img width="326" alt="captura de tela 2019-03-05 as 17 18 58" src="https://user-images.githubusercontent.com/48183960/53834917-f7eb7f80-3f6a-11e9-8bb3-f857852c9d43.png">

Is the option implemented for media players? Didn't find it in the code in a quick look.

Thanks!

**Comment by thomasloven** [comment]
That seems to be a bug. Please open a new issue for it so I can keep track.

**Comment by MightyMilster** [comment]
Hi again. Im running HA 0.89.1 and just updated my card to the latest version. That last update seems to leave blank canvas where the slider would be, had the entity been available.

See below, Shed Light 1 and 2 have sliders.

![Screenshot_20190309-091953_Chrome~01](https://user-images.githubusercontent.com/43132848/54062016-b9e6a800-4257-11e9-8fe8-91627d1f3966.jpg)

**Comment by tomeeka** [comment]
Hi Thomas, so is this fixed? Or wont be?

**Comment by thomasloven** [comment]
Sorry. I was confused by the multiple unrelated questions that popped up along the way.

**Comment by thomasloven** [comment]
Should be fixed in v0.1
