### ISSUE TITLE
Grow doesn't seem to work?

### ISSUE THREAD

**Issue by froman753** [thomasloven/lovelace-slider-entity-row#232]
I have tried changing the grow attribute to true but it doesn't make a difference whether it's true or false, the  slider remains the same length.

**Comment by paranoidi** [comment]
Same. I'd love to get rid of tons of sprinkled css and just use this. But this is not it (yet).

I'd love if there were options to accomplish this.

```
    card_mod:
      style:
        hui-generic-entity-row:
          $: |
            .info {
              display: none !important;
            }
          .: |
            ha-slider {
              max-width: unset !important;
            }
```

**Comment by thomasloven** [comment]
The effect is very slight - as documented - but it's as much as the entities card allows.
