### ISSUE TITLE
Can't load repo on Hassio

### ISSUE THREAD

**Issue by dpudia** [thomasloven/lovelace-slider-entity-row#24]
Hi,
I have a problem to import your repo in Hassio 0.86.3
I use this url:
https://github.com/thomasloven/lovelace-slider-entity-row
This is that I readed through logs:

19-01-31 13:59:01 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/thomasloven/lovelace-slider-entity-row repository
19-01-31 13:59:05 WARNING (MainThread) [hassio.addons.data] Can't read repository information from /data/addons/git/2a017cbb/repository.json
19-01-31 13:59:05 INFO (MainThread) [hassio.addons] Load add-ons: 53 all - 0 new - 0 remove

**Comment by thomasloven** [comment]
You can't what what on what?

[Installtion instructions](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins)
