### ISSUE TITLE
Allow secondary_info with custom attribute when state is off

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-slider-entity-row#240]
Currently it is not possible to show secondary_info with custom (non-default) attribute when state is off.

Allow a `secondary_info` (like `brightness` or `brightness_pct`) when entity's state is off.
Perhaps divide them into
- `secondary_info_on` and
- `secondary_info_off`

**Target:** use `secondary_info_on: brightness_pct` when on and `secondary_info_off: last-updated` when off.

State on is fine:
![grafik](https://user-images.githubusercontent.com/13799156/155852993-300d933f-ea9b-4cec-81b9-754571cbb6de.png)

State off is missing secondary_info:
![grafik](https://user-images.githubusercontent.com/13799156/155853012-cf5cc2cd-da5d-4427-88ab-8e07b80f1d2c.png)

Used for example:
```
  - type: custom:slider-entity-row
    entity: light.lampe_tisch
    name: Lampe Tisch
    hide_when_off: true
    full_row: false
    min: 1
    max: 100
    step: 1
    attribute: brightness_pct
    toggle: true
    show_state: true
    state_color: true
    secondary_info: brightness
    state_header: ''
    column: false
```

**Comment by Santanachia** [comment]
try to use this: https://github.com/custom-cards/secondaryinfo-entity-row

**Comment by thomasloven** [comment]
Anything to the left of the slider is handled by Home Assistant and will only have the features that any other row has.

**Comment by thomasloven** [comment]
Yes. In exactly the same way as slider-entity-row does. No more. No less.

**Comment by bcutter** [comment]
So wait, just to make this clear (I probably didn't understand you right) or to sum up what I understood:

I can have either `secondary_info: brightness` OR `secondary_info: last-changed`. You closed it as "completed" while that would rather be "not possible".

Maybe card-mod can do some magic here. Otherwise I'm out of ideas.
