### ISSUE TITLE
Slider is not scaled to fit card (e.g. in horizontal-stack)

### ISSUE THREAD

**Issue by AleXSR700** [thomasloven/lovelace-slider-entity-row#249]
My Home Assistant version: 2022.4.7

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
I am trying to create a horizontal-stack with a slider in one of the columns

What I expected to happen:
The slider should always start and end inside its column just like buttons etc. are scaled to fit the column.

What happened instead:
Slider starts outside of the card
![image](https://user-images.githubusercontent.com/57034871/166057287-9a7fcd43-e843-4f34-87d5-6cff36112705.png)

**Minimal** steps to reproduce:
Create horizontal stack with e.g. 5 cards and put slider in the left one.

```type: horizontal-stack
cards:
  - type: entities
    entities:
      - type: custom:slider-entity-row
        entity: climate.eq_3_living_room
        name: Living Room
        full_row: true
        min: 4.5
        max: 23
        step: 0.5
        hide_state: false
  - type: button
    show_name: false
    show_icon: false
    tap_action:
      action: none
    hold_action:
      action: none
    entity: sensor.eq_3_battery_living_room
    show_state: true
  - type: custom:button-card
    color-type: blank
  - type: button
    show_name: false
    show_icon: true
    tap_action:
      action: toggle
    entity: sun.sun
  - type: button
    show_name: false
    show_icon: true
    tap_action:
      action: toggle
    entity: sun.sun
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
See the note in this old version of the layout-card readme for an explanation: https://github.com/thomasloven/lovelace-layout-card/tree/8eeea0e700adcd82c42a255b111891ec0c663e0d#tweaking-layouts
