### ISSUE TITLE
Hide slider if toggle shown and device state is off

### ISSUE THREAD

**Issue by janjurek** [thomasloven/lovelace-slider-entity-row#25]
Hello, I'd really like the ability to hide slider for specific row, when toggle is shown. That way when light is i off state it would give me better feedback about it. Would that be possible?

**Comment by thomasloven** [comment]
`hide_when_off: true`

**Comment by janjurek** [comment]
Oh It really is there, sorry about that, there was no mention about it in the readme, so I didn't know about that. Thanks!
