### ISSUE TITLE
Toggle switch opens up extra options

### ISSUE THREAD

**Issue by dragosdmc** [thomasloven/lovelace-slider-entity-row#253]
I am using the slider entity with a climate entity. The slider controls the temperature and i also have a toogle for the a/c to go on and off. On the desktop interface the button works fine, but in the iphone app when i press the toggle button is pops up the aditional options for the a/c. How can i make it that the toggle switch only toggles the power on and off?

**Comment by nochlab1** [comment]
Same issue on android app

**Comment by thomasloven** [comment]
Please try release 17.3

**Comment by nochlab1** [comment]
Works now thanks
