### ISSUE TITLE
state_color: true

### ISSUE THREAD

**Issue by creeve4** [thomasloven/lovelace-slider-entity-row#254]
When using the option `state_color: true` it is not applied to the icons belonging to entities which use your slider-entity-row.

**Comment by klessed** [comment]
In the home assistant entities card the state_color property is not passed on for custom row types (or a conditional row). Setting an extra state_color property to the slider-entity-row works:
      - type: custom:slider-entity-row
        entity: cover.mancave
        step: 1
        hide_state: false
        **state_color: true**

**Comment by ildar170975** [comment]
Is this issue resolved?

**Comment by creeve4** [comment]
> Is this issue resolved?
Yes

**Comment by ildar170975** [comment]
then close it if resolved
