### ISSUE TITLE
Additional dot

### ISSUE THREAD

**Issue by Santanachia** [thomasloven/lovelace-slider-entity-row#261]
Could you add a gray dot for current temperature for climate entity?
Like this:
![Screenshot_2022-12-02-21-02-46-348-edit_io homeassistant companion android](https://user-images.githubusercontent.com/4628507/205376400-c65143f9-e5c0-43b1-8e29-68d01b859630.jpg)

**Comment by thomasloven** [comment]
This is not supported by the slider that Home Assistant uses.
