### ISSUE TITLE
Installation with HACS does not work

### ISSUE THREAD

**Issue by karloslb** [thomasloven/lovelace-slider-entity-row#265]
I'm trying to install the card with HACS.
Downloading will not finish,
![grafik](https://user-images.githubusercontent.com/118773569/209968967-5ae277ec-769d-41b4-b7aa-c68cbfab1738.png)
What can I do?
Do I have to prepare something beforehand? Install something extra?

**Comment by commentsonly** [comment]
yep fails completely unsure why ...
but i's not the first time HACS fails installing things it does list. So I really wonder if that's a HACS problem in the end.

**Comment by karloslb** [comment]
hi,
thanks for your answer
