### ISSUE TITLE
Add support for mapping

### ISSUE THREAD

**Issue by toolCollection92** [thomasloven/lovelace-slider-entity-row#266]
A mapping support would be awesome.
Example: My Onkyo receiver has a volume range from 0-80. Setting the slider to 50%(0.5) sets the volume to 40.
Additional attributes send_min and send_max which would map 0-80 to 0-100% would be highly appreciated.

Example config for my onkyo:
`  - type: custom:slider-entity-row`
`    entity: media_player.receiver`
`    min: 0`
`    max: 80`
`    send_min: 0`
`    send_max: 100`

This would send 0.5 when the slider is set to 40 and the volume 40 would be set.
thanks!

**Comment by thomasloven** [comment]
I suggest you report this bug to the onkyo integration maintainer instead.
