### ISSUE TITLE
Hold triggers a right click on the background image

### ISSUE THREAD

**Issue by rvisser88** [thomasloven/lovelace-slider-entity-row#270]
![20230306_210104_1](https://user-images.githubusercontent.com/51273481/223218487-c15f87d3-e148-4c79-a386-e8581ba5d8ca.gif)

I use the newest version of HA.

Holding the slider knob still and pressed, triggers a right mouse click on the background image.

Love your work though!!!
And very sorry when it is not a bug, but my code :)

Greetings,
Rick

Code:
`  - type: custom:slider-entity-row`
`    entity: climate.a_woonkamer_2`
`    min: 10`
`    max: 25`
`    step: 0.5`
`    hide_state: true`
`    full_row: true`
`    card_mod:`
`      style: |`
`        ha-slider {`
`         --paper-slider-container-color: rgb(204,102,0);`
`         --paper-progress-active-color: rgb(51,102,255);`
`         --paper-slider-knob-color: white;`
`        }`
`    style:`
`      top: 63%`
`      left: 29.81%`
`      width: 20%`
`      transform: translate(-50%, -50%)`

**Comment by thomasloven** [comment]
Use outside of entities cards is unsupported.
And this seems to be some android base functionality which I can't do much about.
