### ISSUE TITLE
Cover buttons + slider between text and buttons

### ISSUE THREAD

**Issue by gryzli133** [thomasloven/lovelace-slider-entity-row#275]
I saw already few requests like this. How hard would it be to get this done:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/30415928/32c0ea24-161a-4936-a928-3b92bad0b956)

Until now your solution was like adding an extra row:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/30415928/3e7da2b9-68f1-44e1-85d6-e633fe18bc08)

But even using tabbed card, flod entity rows etc. my overview dashboard is already out of space. having the ability to place the slider inside the cover row will help me a lot.

**Comment by thomasloven** [comment]
Sure. I can add that.
But since Home Assistant enforces a certain width allocated for the name, it will not look good:
![bild](https://github.com/thomasloven/lovelace-slider-entity-row/assets/1299821/7225c537-ec3d-417f-b285-7ed592b4e09a)
