### ISSUE TITLE
Support for Fan components

### ISSUE THREAD

**Issue by declankenny** [thomasloven/lovelace-slider-entity-row#28]
First off, I have to say that I am a huge fan of all you are doing for the Lovelace UI. So thanks for everything.

Can I ask that you include support for the fan domain?
https://www.home-assistant.io/components/fan/

**Comment by gabe565** [comment]
I have added this in my pull request #27.

Hasn't been merged in yet but I have been using it for about a week now and it is working great for me. Could use some more testing if you wanted to [download the version in the pull request](https://github.com/thomasloven/lovelace-slider-entity-row/blob/8626f1bdacc53237516549fd3067270ad25c425f/slider-entity-row.js)!

**Comment by declankenny** [comment]
I just pulled the latest version and can confirm that the fan domain is now working as expected. Thanks guys.
