### ISSUE TITLE
Support for Sensor

### ISSUE THREAD

**Issue by t-abraham** [thomasloven/lovelace-slider-entity-row#287]
Is there any possibility to support the slider for the `sensor` class `entity`.

I would like to control the sensitivity of various sensors which has either `float value` or a `dict of attributes`. So having this will allow to control custom variables created for automation using [hass-variables](https://github.com/enkama/hass-variables)

**Comment by thomasloven** [comment]
A `sensor` cannot be controlled from Home Assistant. They present sensed values.
