### ISSUE TITLE
Line of the slider dissapeared on ipad

### ISSUE THREAD

**Issue by dolezeldavid** [thomasloven/lovelace-slider-entity-row#288]
My Home Assistant version: 2023.11.3

My lovelace configuration method (GUI or yaml): yaml

What I am doing: I have a shutter using the custom:slider-entity-row - it was working, but few days ago the slider line dissapeared in HA app in my ipads. The line is visible and working normally on PC and iphone, but not on ipad anymore

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```type: entities
entities:
  - entity: cover.rolety_loznice_zigbee
    name: Rolety ložnice
    type: custom:slider-entity-row
    hide_when_off: false
    grow: true
    state_color: true
    secondary_info: last-changed

# End of code
```

Error messages from the browser console: Not indicating any error, the line is just missing

ipad:
![2023-11-26 16 42 50](https://github.com/thomasloven/lovelace-slider-entity-row/assets/130760923/aad79d7e-2c35-43aa-82c8-fb236716c8c4)

the same on PC:
![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/130760923/72ecddb4-a3ad-462f-9726-ca25c8931782)

the same on iphone: 
![2023-11-26 16 46 27](https://github.com/thomasloven/lovelace-slider-entity-row/assets/130760923/24b5816f-5799-4c3f-871b-28c431a82e61)

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
https://github.com/thomasloven/lovelace-slider-entity-row/issues/281

**Comment by dolezeldavid** [comment]
#281 worked for me, thank you!
