### ISSUE TITLE
Support for sensor entity's

### ISSUE THREAD

**Issue by chrkov** [thomasloven/lovelace-slider-entity-row#294]
My Home Assistant version: 0.XXX.X  2024.1.3

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Trying to use this on a MQTT sensor.

My code is simple:

      - type: custom:slider-entity-row
        entity: sensor.cmk_od_fpplot99t2
        attribute: Volume
        step: 1
        full_row: false
        name: Volume

What I expected to happen:
its works.

What happened instead:
I get the following error:
![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/57808614/9906d679-aa7e-49e1-ac56-2e9b4e658920)

Does this not support a sensor entity as it says or is this a bug?  Not sure which is why I am asking.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
The point of the slider is to change the value. Sensors cannot be changed.

Would be nice to be able to pull `sensor.bank_account_balance` a bit to the right, but it doesn't make sense.
