### ISSUE TITLE
Entities header slider

### ISSUE THREAD

**Issue by deejcunningham** [thomasloven/lovelace-slider-entity-row#295]
It would be convenient to be able to add a slider to the Entities Card header that controls all slide-able Entities in the card.

Currently the only way that I know to accomplish this is to create a Group and then give that Group a separate row in the Entities card like so:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/30193983/c20ddf45-e0ac-4221-a3ba-58aef679cd1c "`light.primary_bedroom_lamps` is a Group of all the lights below it.")

This isn't a terrible solution, but it does mean that I have to manage both the Group and this Entities Card separately - e.g. if I add a new light I need to remember to update both the card and the Group. I also think it doesn't look _quite_ as nice as having the slider in-line with the header label and toggle (like the entity rows are).

This would probably be incompatible with Entities Cards that contain a mixture of slide-able Entities from different domains - i.e. `light`s and `climate`s and `media_player`s and `fan`s. Though it might be possible to define which domain the header-level slider applies to - i.e. only `light`s?

**Comment by ildar170975** [comment]
If you suggest to add a possibility to display this custom card inside a header of the standard Entities card - doesn't it mean that you suggest to change the Entities card itself?

**Comment by thomasloven** [comment]
The entities card also has a `header` property which can be used:

https://www.home-assistant.io/dashboards/entities/#header

The implementation seems a little bit buggy, though, so it requires a bit of workarounds.

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/1299821/8a62424f-ac83-4ad6-9704-8de7000402fe)

**Comment by deejcunningham** [comment]
Very cool @thomasloven - thanks!
