### ISSUE TITLE
Name of input_number is not shown when full-row

### ISSUE THREAD

**Issue by abattech** [thomasloven/lovelace-slider-entity-row#30]
When full_row is true, the name is not shown for my input_number entity, only the slider and the current value.
My config:

`      - entity: input_number.living_room_temperature_target
        name: Temperature Target
        type: custom:slider-entity-row
        full_row: true
`

**Comment by thomasloven** [comment]
Yes. That's what full_row does.

**Comment by rjgrandy** [comment]
I think I am seeing this as well

I do the full_row and I get the slider and value, but no name, icon and toggle above it like in your examples.

![image](https://user-images.githubusercontent.com/34561734/56114529-bca77d80-5f26-11e9-99f2-775be5f518d1.png)

**Comment by thomasloven** [comment]
Yes. That's what full_row does. It extends the slider to the full row, showing nothing but the slider and the value or switch depending on other settings. It's exactly what it's supposed to do.

**Comment by rjgrandy** [comment]
Thanks for the reply, I see it now, I missed that there is 2 lines with the same entity (light.bed_light) to make what I was trying to copy.

 - entity: light.bed_light
 - type: custom:slider-entity-row
   entity: light.bed_light
   full_row: true
