### ISSUE TITLE
Change slider increment 

### ISSUE THREAD

**Issue by Asmegin** [thomasloven/lovelace-slider-entity-row#34]
I am using a slider to display a input_number but it only displays whole numbers. When I use the slider it follows the input_number increment setting (0.5) but it won't display once I let go of the slider.

**Comment by rensenti** [comment]
Hi, yes - this is an issue for me as well. slider-entity-row is not aware of floats, even though it recognizes the defined step (in my example it's 0.01)

[Screenshot 1](https://i.imgur.com/KQBbJBL.png) - tried to set the input_number via slider-entity-row 3.18, but it gets set to 3 (3.0 actually)

[Screenshot 2](https://i.imgur.com/UEAmcEA.png) - when a float value like 4.37 is set through 'normal' input_number entity it works, but it's not visible in the custom-entity-slider

**Comment by thomasloven** [comment]
This might be fixed in v0.1. Please let me know if it works.

**Comment by rensenti** [comment]
Hi, thanks for your reply. 

input_number can now be modified to a float value with slider-entity-row, but the value is still not displayed correctly: https://i.imgur.com/ifrpY2P.png
