### ISSUE TITLE
Get NaN % when using default settings with media_player

### ISSUE THREAD

**Issue by laos62** [thomasloven/lovelace-slider-entity-row#36]
Hi, I am trying to use this for media player volume control, but get "not a number % (NaN %) on right side while using default settings. I also get it with settings below (tried it since it looks like volume should be between 0-1). Using latest hass.io 0.90.1
![Skärmklipp](https://user-images.githubusercontent.com/45151527/55033112-afc3f800-5012-11e9-9ff8-dea76161636c.PNG)
 
  - title: 'Mediaspelare'
    icon: mdi:video-vintage
    cards:
    - type: entities
      title: Ljudvolym
      show_header_toggle: false
      entities:
      - type: section
        label: Mediaspelare
      - type: custom:slider-entity-row
        entity: media_player.lg_vardagsrum
        min: 0
        max: 1
        step: 0.1

**Comment by thermseekr** [comment]
I get that when my media players are off. I tried hide_when_off but the slider don’t hide. I opened an issue about this.

**Comment by thomasloven** [comment]
Should be fixed with #37
