### ISSUE TITLE
Slider does not update real time position and percentage when curtain roller is moving

### ISSUE THREAD

**Issue by jerrychong25** [thomasloven/lovelace-slider-entity-row#39]
Hi all,

I have installed Lovelace slider entity row integrated with my curtain roller.

However, when I move the curtain from **0%** to **50%** via the slider, the slider does not update real time position and percentage when moving, as per screenshot below:
![Curtain Precentage Not Update Real Time](https://user-images.githubusercontent.com/15714095/55452947-66743980-560c-11e9-89db-2bcc0d19a555.gif)

It will only displays the final position and percentage after the movement is finished.

So, how could I do to update real time position and percentage when moving?

Thanks.

**Comment by thomasloven** [comment]
It updates whenever the cover reports a new position.

**Comment by jerrychong25** [comment]
> It updates whenever the cover reports a new position.

So this means that it is hardware issue, which we can't control at all?

**Comment by thomasloven** [comment]
Hardware or something with the integration.
It could also just be latency; lovelace doesn't quite get live updates from the backend. Close, but not quite.

**Comment by PierreScerri** [comment]
Hi,
I'm experiencing the same issue with a Sonoff Dual (flashed with ESPHome time-based cover) controlling a dumb shutter.  The position slider in the 'More Info' box updates in real time.  Isn't this what slider-entity-row displays?
