### ISSUE TITLE
Multiple entities one slider

### ISSUE THREAD

**Issue by sebastiaan001** [thomasloven/lovelace-slider-entity-row#4]
Love the slider! Can you make it possible to use one slider for multiple lights?

**Comment by edif30** [comment]
why not just group the lights in HA via the light component, then use this slider for that light that combines multiple?

**Comment by sebastiaan001** [comment]
Then you cant adjust the individual lights in the light group.

**Comment by thomasloven** [comment]
How would this be any different?

**Comment by sebastiaan001** [comment]
With the light group the group behaves as one light. I would like to have a slider for multiple lights but keep the control over the individual lights.

**Comment by thomasloven** [comment]
I've tried it now, and with a light group I can controll all lights together or each light individually, so I don't understand what you are asking for?

**Comment by sebastiaan001** [comment]
Oke, then i am doing something wrong i think, thanks.
