### ISSUE TITLE
help out for those with right to left languages

### ISSUE THREAD

**Issue by refael65** [thomasloven/lovelace-slider-entity-row#40]
Hi thomasloven.
i’m using the “slider entity raw” witch is great
when i changing HA language to Hebrew witch is from right to left
the dimmer slider is acting opposite,
can you help out for those with right to left languages
Thanks
Refael

**Comment by micronen** [comment]
Hi thomas, 
I still have a problem with RTL (Hebrew) mode. 
When I click the slider, the position changes to 1-<value clicked>.
If I want to get to 90%, I need to click the slider at 10% 

Can you please check it out?
Thanks, Ronen.

**Comment by micronen** [comment]
Here is another example of the RTL problem,
In the GIF, I'm holding the right mouse button and dragging the slider.
To make the slider go left, I need to move the mouse to the right, and vice versa.
Pretty funny, but not so useful

![1](https://user-images.githubusercontent.com/4703861/63652922-e3947c80-c76e-11e9-9905-e475c947985d.gif)

Thanks,
Ronen

**Comment by thomasloven** [comment]
Seems I forgot about RTL support in the rewrite.
Sorry.
