### ISSUE TITLE
Cover Slider Looks Broken

### ISSUE THREAD

**Issue by soloam** [thomasloven/lovelace-slider-entity-row#41]
Hello, the cover slider looks broken:

            - type: entities
              title: Janelas
              show_header_toggle: false
              entities:
                - type: custom:slider-entity-row
                  entity: cover.livingroom_cover1
                  full_row: false
![image](https://user-images.githubusercontent.com/11949987/55967631-89d55f00-5c72-11e9-9587-4c454c638206.png)

            - type: entities
              title: Janelas
              show_header_toggle: false
              entities:
                - type: custom:slider-entity-row
                  entity: cover.livingroom_cover1
                  full_row: true

![image](https://user-images.githubusercontent.com/11949987/55967683-9eb1f280-5c72-11e9-9c4f-28fe482d854c.png)

From what I understad, full_row: true is what shows the up/down/stop button correct? If I put full_row: true the entity icon and text disappears, and no buttons

Thank You for your work

**Comment by thomasloven** [comment]
No. Compare the picture in the readme to the code posted below it.
`full_row: true` means the slider takes up the full row.

**Comment by soloam** [comment]
So who do I make it to show the up/down/stop controls? In the readme I see:

          - type: custom:slider-entity-row
            entity: cover.hall_window
            full_row: true

Thank you

**Comment by thomasloven** [comment]
When I look in the readme, I see quite a bit more.
Specifically I see a line right above that snippet, which also contains the text "`cover.hall_window`".

**Comment by soloam** [comment]
Oh my good, I'm sorry Thomas... Now I see it... I was so focused on the costume component functions, that I didn't noticed the entity above... I was assuming that it was a property that did that!

Thank you and I'm sorry for the confusion!

**Comment by thomasloven** [comment]
No worries. Hope you like the plugin!
