### ISSUE TITLE
Slider-entity-row card -> control-nob card?

### ISSUE THREAD

**Issue by Tom-ahawk** [thomasloven/lovelace-slider-entity-row#43]
Fits off all, I want to say thanks for all the development you do. I am exited to see the further development of HA/Lovelace and what you people can do with this platform.

One Lovelace card I have bee looking for is a control-nob card. Which I want to use as a volume controller. 

The control-nob should be configurable with: Diameter. Color, on/off-color indicator. Center point (decreasing values/increasing values from center point) or 360+/- swivel (+/- 1 click). Configurable clicks per 360 decrees…

Since you have a developed the slider-entity-row card, maybe a control-nob card could be a variant of this, with time?
![image](https://user-images.githubusercontent.com/35527507/56196215-ad175a00-6036-11e9-9e31-0771df02f0dc.png)

Cheers!

**Comment by thomasloven** [comment]
Thank you for your kind words.

Prettifications like this isn't really my cup of tea, and I prefer to stay within ti Material Design Guidelines.
