### ISSUE TITLE
Toggle lock when using slider?

### ISSUE THREAD

**Issue by nolenjohan** [thomasloven/lovelace-slider-entity-row#44]
Would it be possible to add a feature to use toggle lock (as your: lovelace-toggle-lock-entity-row) also when using this slider function? I guess this would be an enhancement in such case.
![screenshot 827](https://user-images.githubusercontent.com/34334118/56805275-cedbc280-6828-11e9-9a37-a284f65c16f8.jpg)

**Comment by RubenDijk** [comment]
Good idea. I use the slider entity row for my dimmers. Every now and then when I scroll through home assistant it changes the dimmer value. a lock function would be ideal.

**Comment by ctrl50** [comment]
has this been implemented yet? if so example code?
just installed the lock but soon realized i cant lock any of my sliders??

**Comment by thomasloven** [comment]
Check out restriction-card https://github.com/iantrich/restriction-card
