### ISSUE TITLE
Two row display

### ISSUE THREAD

**Issue by mynameisdaniel32** [thomasloven/lovelace-slider-entity-row#46]
Maybe this makes more sense as its own card, but I have a few input_numbers where things are getting a bit cramped and having an input_number display over two rows would be perfect.

For example, instead of the below, each of those would have one row with the name and value/unit. And the second row with a full row slider.

I'm not sure I can quite achieve this with two existing rows (i.e. a sliderlesss row and a full row slider). An option to remove the slider from an input_number so I can do this would also be a useful alternative.

![image](https://user-images.githubusercontent.com/24840952/56880309-57fa3000-6a9b-11e9-971e-92714ac8863d.png)

**Comment by thomasloven** [comment]
https://github.com/thomasloven/lovelace-dummy-entity-row

**Comment by mynameisdaniel32** [comment]
I did see that - and it gets me part-way there - but won't let me put the value on the first row which would be very handy for some longer numbers I'm displaying.

**Comment by thomasloven** [comment]
Try `type: custom:hui-text-entity-row` then.

**Comment by mynameisdaniel32** [comment]
Hadn't come across that one - thanks!

Only problem is it adds a decimal to my lovely integer numbers (they have a decimal in the state). Despite the steps being greater than zero - I'll raise that as a HA issue though as I can't see any reason for it to behave like that (or I'll create another myriad of template sensors...)

![image](https://user-images.githubusercontent.com/24840952/56940163-c26aa900-6b4b-11e9-8525-a99010c01987.png)
