### ISSUE TITLE
slie slider does not work well in full kiosk

### ISSUE THREAD

**Issue by madmicio** [thomasloven/lovelace-slider-entity-row#49]
I found the following error.
I don't know if it depends on my inexperience.
the slider in fully kiosk browser does not work correctly.
sometimes I move the cursor but nothing happens, sometimes it freezes while I move it, other times it works regularly.
generally if I lose the focus while I'm moving the cursor, I don't get any movement of the cover.

this doesn't happen if I use other browsers.

can you help me?

**Comment by KTibow** [comment]
@madmicio still having this error? It could be the slider's fault instead of slider-entity-row.
