### ISSUE TITLE
Location of current dimmer value

### ISSUE THREAD

**Issue by gerard33** [thomasloven/lovelace-slider-entity-row#5]
Is it possible to show the current dimmer value on the second row and not making it replace the toggle?

Like the screenshot below where the last-changed time is shown.
![screenshot_1](https://user-images.githubusercontent.com/11230573/45320959-497afa80-b544-11e8-9e6c-f596903c54d9.jpg)

**Comment by gerard33** [comment]
I have done some trial and error, but can't get the value on the `secondary` line.

I am not able to get it in the `flex` div in which the name of the entity is, but only in the `flex` div in which the slider is. Can you give me some hints?

![screenshot_1](https://user-images.githubusercontent.com/11230573/46435112-da18b500-c755-11e8-9038-4daf555e2d69.jpg)

**Comment by thomasloven** [comment]
I've been experimenting a bit and it can be done with
`this.shadowRoot.querySelector('hui-generic-entity-row').shadorWoot.querySelector(".flex .info .secondary slot[name=secondary]).innerHTML = this.value` placed in updateSliders.
It's not pretty, and it needs a bit of configuration option checks and such, but it works.

**Comment by gerard33** [comment]
Thanks, but after some more trial and error I have found out that this is not enough hints for me :wink: 

And I guess there is a quote missing in the second `querySelector`.

**Comment by skynet01** [comment]
You can make it semi smart. For example: when enabled the number shows up instead of toggle but clicking the number would toggle it off (so it's like invisible toggle). When slider is at 0 it would show toggle again and hide the number.

**Comment by thomasloven** [comment]
Here's a way to get a custom value into the secondary info spot using card-mod
https://github.com/thomasloven/lovelace-card-mod/blob/master/test/views/tricks.yaml#L163-L170

**Comment by gerard33** [comment]
Thanks! About time to close this issue then 😉
