### ISSUE TITLE
Slide is activated while scrolling in mobile app

### ISSUE THREAD

**Issue by bjptwist** [thomasloven/lovelace-slider-entity-row#54]
My Home Assistant version: 0.92.2

My lovelace configuration method (GUI or yaml):
gui

What I am doing:
Scrolling through ow my covers in iOS mobile app

What I expected to happen:
Slide should not move if I touch over it while scrolling through my list

What happened instead:
Slide is activated and my cover starts to open while I was just scrolling the list without any intention of opening/closing any cover

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by pprazzi** [comment]
+1  

It took me a while to discover why my lights were suddenly on, but I also have the same problem. Sliders now activate my lights when scrolling through the HomeAssistant app on iOS

**Comment by HackThatNow** [comment]
Same here, wondering if there is a solution for it. I do note that the Hassio built in dimmer card, does not have this problem. You can scroll the page, the dimmer will not change...

**Comment by rickvanassema** [comment]
Same problem...

**Comment by nikrolls** [comment]
As this component uses the built-in HA slider element, it may be better to report the issue with them. They would need to slide only when the pointer moves in the direction of the slider, and abort the slide otherwise.

**Comment by gfarag** [comment]
Same here, big issue for me.

**Comment by so3n** [comment]
I hadn't updated from the latest commit for probably half a year. This issue only happened to me yesterday when I pulled in the latest code changes. Makes this component unusable. Going to have to revert to an earlier commit

**Comment by so3n** [comment]
Found the issue is due to this commit https://github.com/thomasloven/lovelace-slider-entity-row/commit/4bc7874546d62fa10a80d80e4741d5a6539c4b61

If you checkout a commit prior to that one, the issue isn't there.

**Comment by robert-alfaro** [comment]
Would be nice to see this as an optional attribute to the custom card. It is a nice feature to turn on and set the light brightness with one single tap. However, you get this problem when scrolling on mobile device.  Is there a way to know the device type viewing the page and dynamically handle the action?

**Comment by so3n** [comment]
100% agree on making it optional. Having it mandatory makes this custom card unusable on mobile device

**Comment by robert-alfaro** [comment]
Thanks!
