### ISSUE TITLE
Custom formatter for values

### ISSUE THREAD

**Issue by ajaquith** [thomasloven/lovelace-slider-entity-row#55]
The custom slider is great. I installed it and it works exactly as advertised. Thanks!

I have a feature request. I would like to be able to format the display values using a template of some sort. For example, my Marantz receiver natively shows its volume in decibels relative to reference volume. I'd like the slider to show "-80 db" for 0%, and "0 db" for 100%. To use another slightly silly example, you could show Hue lamps in lumens rather than %. The formatter would not modify the values that are read from (or sent to) the entity. It would only modify what is shown in the UI. 

Here's a suggested card config:

- entity: media_player.living_room
  type: custom:slider-entity-row
  value_template: 'eval${value * 100 - 80} db'

There are probably other ways to do this.

Thanks for all of the great work, and thanks for considering this request.

**Comment by thomasloven** [comment]
For this to work, you would need to also set max, min and step size manually, and to add conversions for both ways.

I suggest you instead create an `input_number` and perform the conversion with two automations.
