### ISSUE TITLE
Unable to show the slider and error message

### ISSUE THREAD

**Issue by javiergmarcos** [thomasloven/lovelace-slider-entity-row#57]
> My Home Assistant version: 0.95.4, RPi 3B+
>My lovelace configuration method (GUI or yaml): GUI
>What I am doing: Slider to control dimmable lights
>What I expected to happen: Sliders appear
>What happened instead: 
>>- Sliders doesn't appear. The bulb icon, name and percentage appear
>>- When you try to setup the GUI next error arise in setup screen:
Your config is not supported by the UI editor:
Expected a value of type `{entity,name,icon} | entity-id` for `entities.0.type` but received `"custom:slider-entity-row"`.
Falling back to YAML editor.

>**Minimal** steps to reproduce:
>>Checked in Google, Firefox and Safari with same results
>>Google Console doesn't generate any error

>```yaml
lovelace.yaml associated to this card (via edit raw confoguration) :

resources:
  - type: module
    url: /local/plugins/slider-entity-row.js

  - entities:
      - entity: light.luz_indirecta_cc
        type: 'custom:slider-entity-row'
    title: Luces CC
    type: entities

file located at: config/www/plugins/slider-entity-row.js

# The least ammount of code possible to reproduce my error

![Slider-entity-row](https://user-images.githubusercontent.com/27368905/61420582-6e2dc480-a903-11e9-82f3-3f3641077550.JPG)

# End of code
```

Error messages from the browser console:
No error messages (Google Chrome console)
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
The error message is because the GUI editor cannot handle special rows in entities cards, yet. That's unrelated to slider-entity-row.

Could you please find your light in the list in `/dev-entities` and show me the contents of the rightmost column for it, i.e. it's attributes?

**Comment by javiergmarcos** [comment]
The attributes you are asking for were:
 friendly_name and supported_features: 0

After look at several webs, I’ve added next code to the custom light code:

    from homeassistant.components.light import ATTR_BRIGHTNESS, Light, PLATFORM_SCHEMA, SUPPORT_BRIGHTNESS
……….
    @property
    def supported_features(self):
        """Flag supported features. This method is optional. 
        """
        return SUPPORT_BRIGHTNESS

Then the attributes changed to:
	friendly_name, brightness and supported features: 1

The  sliders-entity-row then worked properly.
 
Thanks for your support

**Comment by javiergmarcos** [comment]
Hi Thomas,

 

This is a custom development light.

The attributes you are asking for were:

friendly_name and supported_features: 0

 

After look at several webs, I’ve added next code to the custom light code:

 

    from homeassistant.components.light import ATTR_BRIGHTNESS, Light, PLATFORM_SCHEMA, SUPPORT_BRIGHTNESS

……….

    @property

    def supported_features(self):

        """Flag supported features. This method is optional. 

        """

        return SUPPORT_BRIGHTNESS

 

Then the attributes changed to:

                friendly_name, brightness and supported features: 1

 

The  sliders-entity-row then worked properly.

Thanks for your support

 

I’ve closed the issue

 

Javier González Marcos | +34 638 210 480

Dhomo Solutions | Calle Aurora, 28 | 28035 | Madrid

 

De: Thomas Lovén [mailto:notifications@github.com] 
Enviado el: domingo, 21 de julio de 2019 21:28
Para: thomasloven/lovelace-slider-entity-row
CC: javiergmarcos; Author
Asunto: Re: [thomasloven/lovelace-slider-entity-row] Unable to show the slider and error message (#57)

 

The error message is because the GUI editor cannot handle special rows in entities cards, yet. That's unrelated to slider-entity-row.

Could you please find your light in the list in /dev-entities and show me the contents of the rightmost column for it, i.e. it's attributes?

**Comment by thomasloven** [comment]
Yeah... if the light isn't dimmable, there won't be a dimmer slider...
Glad you solved it!
