### ISSUE TITLE
Ability to completely collapse the slider

### ISSUE THREAD

**Issue by sstratoti** [thomasloven/lovelace-slider-entity-row#65]
I have the slider set under a custom-button-card entity inside of a horizontal-stack.

```
  - type: 'custom:slider-entity-row'
    entity: light.storage
    hide_state: true
    full_row: true
    hide_when_off: true
```
When the light entity is "off" the slider disappears - which is great. But the "wrapper" div that is left behind has a height of 40px. This results in a space existing where the slider used to be.

Light on:

![image](https://user-images.githubusercontent.com/1392597/62552517-c5a4bd80-b83b-11e9-8bd2-1848005d7e55.png)

Light off:

![image](https://user-images.githubusercontent.com/1392597/62552547-d05f5280-b83b-11e9-887b-355b7a74c364.png)

It looks like this is an in-line style inside of the shadow-root, which is difficult to edit from  reading your posts about it. I'm trying to edit it using card-mod, but haven't figured it out yet. Thought about suggesting it as an enhancement.

Thanks!

**Comment by thomasloven** [comment]
https://www.home-assistant.io/lovelace/conditional/

**Comment by sstratoti** [comment]
Hah, I was just about to close this because I found the conditional card. Sorry about that, and thanks!
