### ISSUE TITLE
Cover position jumps to 0 while the cover is in motion

### ISSUE THREAD

**Issue by micronen** [thomasloven/lovelace-slider-entity-row#66]
My Home Assistant version: 0.97.2
My slider version: 5

My lovelace configuration method (GUI or yaml): yaml

What I am doing: clicking the slider to move the cover

What I expected to happen: 
The slider should track the movement of the cover
![1](https://user-images.githubusercontent.com/4703861/63642678-7bd92580-c6cb-11e9-826f-7dbc6515efdb.gif)

Like what the slider in the 'more info' window does:
![2](https://user-images.githubusercontent.com/4703861/63642680-84316080-c6cb-11e9-8db8-807b21b77f30.gif)

What happened instead: the slider jumps to 0 for the duration of the movement

**Minimal** steps to reproduce: click the slider 

```yaml
- type: custom:slider-entity-row
  entity: cover.living_room_big_blinds
```

Error messages from the browser console:
NONE

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Excellent bug report. Thank you!

Unfortunately, I can't reproduce this behavior.
Could you check what `current_position` your cover is actually reporting in `developer-tools/state` while moving?

**Comment by micronen** [comment]
Here is a GIF of the slider and the states at the same time:
![2](https://user-images.githubusercontent.com/4703861/63653087-e85a3000-c770-11e9-90a1-67dfdbced1ee.gif)

I'm using ESPHome with a time based cover configuration.
Do you have a ESP-01 board, or similar?

Ronen

**Comment by micronen** [comment]
Why do you have the following code in cover-controller.js?

lines 9-20:
~~~ c
  get _value() {
    switch (this.attribute) {
      case "position":
        return this.stateObj.state === "open"
        ? this.stateObj.attributes.current_position
        : 0;
      case "tilt":
        return this.stateObj.attributes.current_tilt_position;
      default:
        return 0;
    }
  }
~~~

**Comment by thomasloven** [comment]
Interesting. The demo covers only have states "open" and "closed".
Thanks for the debugging!
