### ISSUE TITLE
entity domains for switches

### ISSUE THREAD

**Issue by chadlyy** [thomasloven/lovelace-slider-entity-row#68]
Can you add a switch domain too?  I have a ton of insteon light switches that I would love to use.

**Comment by thomasloven** [comment]
What would be the difference from the normal toggle?

**Comment by chadlyy** [comment]
My entity is switch.office_fan
when I try to add that as a normal toggle I get:
*Unsupported entity type: switch*

{

  "entity": "switch.office_fan",
  "toggle": true,  "type": "custom:slider-entity-row"

}

The work around is to create a template to make it appear as
light.office_fan but I really don't want to create like 15 templates.
:)

**Comment by thomasloven** [comment]
Why would you want it as a slider? There's nothing to adjust except for on/off.

**Comment by chadlyy** [comment]
Hi Thomas

I'm so sorry!  I was wanting to group all the office lights on one card and
so I was copying the entities and just renaming the lights.  Now I realize
all I had to do was remove the type slider and it works perfectly.
Sorry for the confusion!  Great plugin and thanks for the super
fast response!
