### ISSUE TITLE
Feature Request: Support for Covers

### ISSUE THREAD

**Issue by ITTV-tools** [thomasloven/lovelace-slider-entity-row#7]
Support for covers would be great. (Same as in customUI)

**Comment by pleeja** [comment]
Hi @ITTV-tools, I edited this card to work with covers. It's works but don't try to configure it or it will break. link: https://github.com/pleeja/Lovelace1/blob/master/cover-slider-entity-row.js

@thomasloven A tip for if you ever were to update this card to work with covers: The cover attribute for its position (current_position) is different from the command you send it to set it to a specific position(position). Got stuck on that

**Comment by VDRainer** [comment]
+1
This is exactly what i'm looking for!

**Comment by thomasloven** [comment]
Added!
