### ISSUE TITLE
Error in card configuration

### ISSUE THREAD

**Issue by fernmac2** [thomasloven/lovelace-slider-entity-row#72]
Hello,
Things seem to work as I want but in the card configuration, I got this error:
Expected a value of type `{entity,name,icon} | entity-id` for `entities.0.type` but received `"custom:slider-entity-row"`.
I am running Hass.io 1.12
Thanks

**Comment by thomasloven** [comment]
As with all lovelace cards, that means you're using a feature which is not supported by the GUI editor yet.
