### ISSUE TITLE
Customize: height and colors

### ISSUE THREAD

**Issue by f00dagi** [thomasloven/lovelace-slider-entity-row#73]
Hi, thanks for great work.

I wish to see that the slider-entity-row was more customizable. Since it is often used together with button-card it would be great if it could be really compact and also possible to change slider and knob color to match other cards. Looking at the attached image the slider-entity-row has a height that is unproproportional and it would be nice to make the knob and slider white.

![E4245D20-8640-44E0-B54F-523EFB040A5C](https://user-images.githubusercontent.com/56124786/67432651-e4b71e00-f5e6-11e9-8a55-09e0a9d00c6d.png)

**Comment by thomasloven** [comment]
https://github.com/thomasloven/lovelace-card-mod
