### ISSUE TITLE
Poissible feature request: CSS for card width or create option in card

### ISSUE THREAD

**Issue by vmmlab** [thomasloven/lovelace-slider-entity-row#74]
Hi Thomas,

Having trouble getting the slider to play nice in a horizontal-stack with a custom button card.  Ideally i'd like to be able to specify the width of the slider card so that it shifts the button column more to the left so it scales correctly.  I've looked at your card-modder script but I can't work out the CSS part. 

In the attached image I'd like the 'Wall Lights' button to be sized the same as the buttons above with the slider stretching access the remaining columns.

 Any ideas or help would be appreciated :)

//Ed

![image](https://user-images.githubusercontent.com/31982786/67606830-db62b880-f782-11e9-8052-d7d9357c1bb0.png)

**Comment by thomasloven** [comment]
This is not a a lovelace card. It's a custom row for the entities card.
While it *can* be used as a card, doing so is unsupported.
