### ISSUE TITLE
Invert Slider

### ISSUE THREAD

**Issue by philsson** [thomasloven/lovelace-slider-entity-row#75]
I'm using this slider for my blinders. My problem is the blinders are at "0" when closed and "100" when open. This makes the slider work the opposite way and be at 100% when the blinders are fully open and at 0% when closed.
I think it would be useful to have an attribute "inverted" or something similar to flip the logic.

**Comment by thomasloven** [comment]
Make your own `cover` entity that works the right way.
https://www.home-assistant.io/integrations/cover.template/

**Comment by thomasloven** [comment]
Also see #64.

**Comment by keteflips** [comment]
Please add this option :)
