### ISSUE TITLE
vertical and scalable

### ISSUE THREAD

**Issue by magiva** [thomasloven/lovelace-slider-entity-row#77]
As i have a grid view of lamp buttons, it would be nice if this card was scalable so i can include it in my custom buttons cards and also have the slider of a vertical type

being able to have a call when slider is 0 would be great, this can send an off command for example

**Comment by thomasloven** [comment]
This is *not* a card. See #74.

Moving a brightness slider to 0 turns off a light.

**Comment by magiva** [comment]
erm ok, i understand, but the first 'suggestion' is still valid though isnt it, to be scaleable and a vertical slider within the card

**Comment by thomasloven** [comment]
Not really. This is a row for an entities card, so it scales with the width of the card, and it wouldn't really make sense to have a vertial row as they are conventionally limited to about 50 pixels in height.

**Comment by magiva** [comment]
understood. thanks

**Comment by thomasloven** [comment]
That being said, I have been thinking of making a vertical slider and bar display at some point. But there's a lot before it in the queue...
