### ISSUE TITLE
Allow for muti-line entity

### ISSUE THREAD

**Issue by KenCote** [thomasloven/lovelace-slider-entity-row#81]
Great work on your modules, Thomas.  I use them everywhere.  One enhancement request: allow for multi-line entities without having to declare the entity twice.

Currently I have items like the four below.

![image](https://user-images.githubusercontent.com/9092387/68612315-42be7f00-048a-11ea-867a-1807c7ab39db.png)

There are actually four entities above, but I'm configuring each twice to get the desired result, which is the top line being the entity name and an on/off toggle, the second line is using this module configured with full_row set to true.  I've included a config excerpt below.

Can you allow for a boolean property here (something like "multi_line") that will allow for the entity to be split to two lines, with the slider being below (set full_row = true).
`

      - type: custom:fold-entity-row
        padding: 5
        head: 
          type: custom:slider-entity-row
          entity: light.all_foyer_lights  
          name: All      
        entities:
        - entity: light.above_bedroom_door
        - type: custom:slider-entity-row
          entity: light.above_bedroom_door
          full_row: true
          hide_state: true
        - entity: light.above_daisys_room
        - type: custom:slider-entity-row
          entity: light.above_daisys_room
          full_row: true
          hide_state: true
`

**Comment by gurkburk76** [comment]
I belive i have a similar problem, this should work no ?

t.entity is undefined

type: 'custom:slider-entity-row'
entities:
  - light.shelly_dimmer_f3e890_light_0
  - light.shelly_dimmer_f362f1_light_0
  - light.shelly_dimmer_f3ce54_light_0

**Comment by thomasloven** [comment]
@gurkburk76 No, it should not. "entities" is not "entity".

**Comment by thomasloven** [comment]
The suggestion goes against best practice design rules for lovelace cards. Each entry in the `entities` list should result in a row in the card with approximately the same height.

I suggest using [lovelace_gen](https://github.com/thomasloven/hass-lovelace_gen) or something simillar to simplify the configuration.

**Comment by KenCote** [comment]
My configuration is fine, at for the WAF, I need longer names for the inputs, hence asking for the wrap.

In any case, thanks for responding, I guess.
