### ISSUE TITLE
Samsung Family Hub cannot view slider-entity-row

### ISSUE THREAD

**Issue by cgc007** [thomasloven/lovelace-slider-entity-row#82]
My Home Assistant version: 0.98.4

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Attempting to view `lovelace-slider-entity-row` within a card on my [Samsung FamilyHub](https://developer.samsung.com/family-hub).

What I expected to happen: The slider would appear and function normally.

What happened instead: Error text is inserted into the card. 

**Minimal** steps to reproduce: Load a card a Samsung Family Hub containing a custom card entity.

```yaml
# The least amount of code possible to reproduce my error
  - entity: light.family_room_lights
    name: All
    type: 'custom:slider-entity-row'
```

Error messages from the browser console:
```
Custom element doesn't exist: slider-entity-row

{
 "entity": "light.family_room_lights",
 "name": "All",
 "type": "custom:slider-entity-row"
}
```

I imagine this is a limitation of the browser that the FamilyHub is using, but just in case it is possible to support it, I figured you should at least know it doesn't work. Another note is that the same yaml works on my phone (android 8.0, running Chrome), my wife's phone (iOS, running Chrome), my PC browsers on Chrome, Edge, and Firefox.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
Have you tried clearing the browser's data under Settings and opening it again?

**Comment by SGXander** [comment]
I'm seeing this too. The Family hub fridge is very limited and has no browser cache clear. I've cleared the data from app manager but it's still happening. I think OP may be right that it's a new limitation on the  OS as the markdown cards don't display anything either.
