### ISSUE TITLE
name "slider-entity-row" has already been used with this registry

### ISSUE THREAD

**Issue by narfel** [thomasloven/lovelace-slider-entity-row#86]
My Home Assistant version: Hassio, ha1.102.3, yaml, latest Chrome, latest plugin version

The good news is that it works fine, but i wanted to do due diligence and report it :) When i was looking in the browser logs for a different reason, i came upon these weird error messages:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "slider-entity-row" has already been used with this registry
    at Module.<anonymous> (http://192.168.1.109:8123/community_plugin/lovelace-slider-entity-row/slider-entity-row.js:1:9566)
    at s (http://192.168.1.109:8123/community_plugin/lovelace-slider-entity-row/slider-entity-row.js:1:110)
    at http://192.168.1.109:8123/community_plugin/lovelace-slider-entity-row/slider-entity-row.js:1:902
    at http://192.168.1.109:8123/community_plugin/lovelace-slider-entity-row/slider-entity-row.js:1:911
```
They also show up in the hassio log as a mystifying "2019-12-04 13:18:15 ERROR (MainThread) [frontend.js.latest.201911196] http://<internal ip>:8123/lovelace/0:0:0 Uncaught". Truncated like that. Any idea what that is?

**Comment by thomasloven** [comment]
Yeah. That happens when you use the Refresh button to reload lovelace changes.
That makes all plugins be loaded again, but since they are alreay registered they can't be... so you get a warning that can be safely ignored.
