### ISSUE TITLE
Add custom secondary info

### ISSUE THREAD

**Issue by VidBalek** [thomasloven/lovelace-slider-entity-row#87]
Would it be possible to get some secondary info in slider entity row? I have something like this in mind:
https://github.com/custom-cards/secondaryinfo-entity-row

I am not sure if that is even possible but it would be a great feature to have.

**Comment by thomasloven** [comment]
I don't think that's in scope for this plugin, but you can use a trick like this: https://github.com/thomasloven/lovelace-card-mod/blob/master/test/views/tricks.yaml#L163-L170
