### ISSUE TITLE
When lights is on, the icon fades out - possible to reverse this?

### ISSUE THREAD

**Issue by Shaun-Harrison** [thomasloven/lovelace-slider-entity-row#89]
My Home Assistant version: 0.103.6

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
When using slider entity row - when the light is turned on, the icon gets dimmed, when light is off they display as normal, would be good to be able to reverse this so that when lights are off it is dim, when on it is lighter to signify light is on

See dining room light icon is dimmed 
![image](https://user-images.githubusercontent.com/46562010/72195054-7b39f500-3408-11ea-9f5f-4d0538dde5c2.png)

**Comment by thomasloven** [comment]
This is default functionality of Home Assistant.
When lights are off, they have the off color, when they are on they have the on color. Dimmable lights fade corresponding to their brightness level, colored lights get colored icons.
