### ISSUE TITLE
Be a base card type

### ISSUE THREAD

**Issue by Spartan-II-117** [thomasloven/lovelace-slider-entity-row#9]
If called as the main card type, this card causes a blank screen, this prevents it from being used on dynamic cards like Monster-Card

**Comment by Spartan-II-117** [comment]
Im not sure which side the issue is, so i filed a bug with Monster card as well:
https://github.com/ciotlosm/custom-lovelace/issues/212

**Comment by thomasloven** [comment]
See the second [example](https://github.com/ciotlosm/custom-lovelace/tree/master/monster-card#examples) in the monster-card documentation for how to set options (such as `type`) for each entity in a monster card.
