### ISSUE TITLE
Add left margin to .state class

### ISSUE THREAD

**Issue by SBado** [thomasloven/lovelace-slider-entity-row#91]
Please, consider adding a left margin to the `.state` class.

Without margin:

![without_margin](https://user-images.githubusercontent.com/16034687/72618674-e8371880-393b-11ea-9585-1b559c214374.jpg)

With 5px left margin:

![with_margin](https://user-images.githubusercontent.com/16034687/72618685-ec633600-393b-11ea-99e4-4f7b427d989e.jpg)

**Comment by thomasloven** [comment]
Can't believe I missed that! Thank you!
