### ISSUE TITLE
Add ability to animate (Blink and Spin)

### ISSUE THREAD

**Issue by chansearrington** [thomasloven/lovelace-slider-entity-row#92]
Hey there, love your slider-entity-row.

One thing I'd really like is the ability to animate my fan icon when the fan is on = spin

I have this functionality from my cutom button entity provider and I'm hoping you can bring that functionality over here as well. 

https://github.com/custom-cards/button-card/releases/tag/0.2.0

**Comment by skynet01** [comment]
I second this request. This will solve the biggest issue i have with home assistant: figuring out when my fan is moving without looking at it 👌

**Comment by thomasloven** [comment]
That's not in scope for this plugin.
Look forward to an upcoming update to my card-mod plugin, though...
