### ISSUE TITLE
Add language support to state

### ISSUE THREAD

**Issue by ptitmickey** [thomasloven/lovelace-slider-entity-row#93]
Thanks for your amazing plugin.

I'm using to add some informations to light entity like brightness and color temperature.
But it could be nice if you can add system language support to show state.

For example, I'm speaking french. So I would like to see "indisponible" instead of "unavailable"
which is correct with first row of lovelace entity card.

![image](https://user-images.githubusercontent.com/10517940/73067335-b75d6300-3ea8-11ea-96ef-84e2f8781c58.png)

![image](https://user-images.githubusercontent.com/10517940/73067404-e1168a00-3ea8-11ea-994d-e7937d45b70b.png)

**Comment by KTibow** [comment]
I think you could do this by getting the `state.default.unavailable` from `hass.resources[hass.language]`.
