### ISSUE TITLE
Support for groups

### ISSUE THREAD

**Issue by trondtorsoe** [thomasloven/lovelace-slider-entity-row#94]
Hi
First of all - nice card!

But...

I have several rooms with 4-8 downlights. It would be nice to have one slider to operate the "light-group" instead of several individual downlights...

Is that possible?

**Comment by thomasloven** [comment]
Yes, by using the *actual* light group, which exists exactly for this purpose: https://www.home-assistant.io/integrations/light.group/

**Comment by trondtorsoe** [comment]
Hi
I am aware of the light.group - but that card is limited to on/off.

All bilbs are dimmable - so I would like to use the slider :-)

![dimm_group](https://user-images.githubusercontent.com/50380501/73466620-69ea6580-4382-11ea-8677-22765b5e7784.png)

**Comment by thomasloven** [comment]
What card?

**Comment by trondtorsoe** [comment]
https://github.com/thomasloven/lovelace-slider-entity-row

Card-code:

entities:
  - entity: group.lys_kjokken
    name: Peisestue 7x dimmer bulbs (group)
    type: 'custom:slider-entity-row'
  - entity: light.spisestue1
    name: Single light :-)
    toggle: true
    type: 'custom:slider-entity-row'
title: Multi room dimmer
type: entities

![error_group_dimmer](https://user-images.githubusercontent.com/50380501/73521696-f9d1f300-4406-11ea-9c17-64eb243d4f04.png)

**Comment by thomasloven** [comment]
Try using a light group, which exists exactly for this purpose: https://www.home-assistant.io/integrations/light.group/ instead. That creates a new `light` entity which controlls all of them together.

**Comment by trondtorsoe** [comment]
Works perfect - thank you Thomas :-)

![it_works](https://user-images.githubusercontent.com/50380501/73589808-8a7a0300-44db-11ea-9276-6db31af0faba.png)
